/**
 * speech / brewList / federation 须与 fixtures 及后端 TappPermission /
 * PERMISSION_LEVELS 同步。先改 fixtures。
 */

import type { PermissionLevel, TappPermission } from '../types'

type TappPermissionLevel = Exclude<PermissionLevel, 'public'>

export const PERMISSION_LEVELS: Record<TappPermission, TappPermissionLevel> = {
  'widget:register': 'privileged',
  'platform:read': 'basic',
  'platform:write': 'privileged',
  'platform:register': 'privileged',
  'analytics:read': 'basic',
  'ai:generate': 'elevated',
  'ai:analyze': 'elevated',
  'ai:chat': 'elevated',
  'ai:image': 'elevated',
  'ai:search': 'elevated',
  '3d:generate': 'elevated',
  'report:read': 'basic',
  'report:write': 'privileged',
  'storage:read': 'basic',
  'storage:write': 'elevated',
  'ui:notification': 'basic',
  'ui:fullscreen': 'basic',
  'ui:theme': 'basic',
  'ui:confirm': 'basic',
  'ui:openUrl': 'basic',
  'network:fetch': 'elevated',
  'media:control': 'basic',
  'media:read': 'basic',
  'media:audio': 'basic',
  'component:theme': 'elevated',
  'component:agent': 'privileged',
  'shortcut:register': 'elevated',
  'event:publish': 'elevated',
  'event:subscribe': 'basic',
  'scheduler:register': 'elevated',
  'speech:tts': 'elevated',
  'speech:asr': 'elevated',
  'tappList:read': 'basic',
  'tappList:manage': 'privileged',
  'brew:read': 'basic',
  'brew:write': 'basic',
  'brew:commentWrite': 'elevated',
  'brew:manage': 'privileged',
  'federation:read': 'basic',
  'federation:post': 'elevated',
  'federation:interact': 'basic',
  'federation:channel': 'elevated',
  'federation:room': 'elevated',
  'federation:ring': 'basic',
  'federation:message': 'basic',
  'federation:trust': 'privileged',
  'federation:files': 'basic',
  'game:session': 'basic',
}

export const PERMISSION_MAP: ReadonlyMap<string, TappPermission | 'public'> =
  new Map([
    ['lifecycle.ready', 'public'],
    ['lifecycle.error', 'public'],
    ['ui.getTheme', 'public'],
    ['ui.getPrimaryColor', 'public'],
    ['ui.getLocale', 'public'],
    ['ui.setTitle', 'public'],
    ['context.getApp', 'public'],
    ['context.getUser', 'public'],
    ['context.getPlayer', 'public'],
    ['context.getNavigation', 'public'],
    ['context.getSystem', 'public'],
    ['context.getGeo', 'public'],
    ['persona.get', 'public'],
    ['user.getRole', 'public'],
    ['user.isAdmin', 'public'],
    ['user.isGuest', 'public'],
    ['user.isLoggedIn', 'public'],
    ['user.getAllowedPermissionLevels', 'public'],
    ['user.canUsePermissionLevel', 'public'],
    ['component.list', 'public'],
    ['shortcut.list', 'public'],
    ['background.list', 'public'],
    ['background.has', 'public'],
    ['animation.getLevel', 'public'],
    ['animation.shouldAnimate', 'public'],
    ['animation.getConfig', 'public'],
    ['animation.getStaggerDelay', 'public'],
    ['dynamicContent.get', 'public'],

    // 权限由后端检查。
    ['api.execute', 'public'],
    ['api.list', 'public'],

    // 双方 manifest + Runtime Grant + 每次宿主授权；无长期静态权限。
    ['dataExchange.registerProvider', 'public'],
    ['dataExchange.unregisterProvider', 'public'],
    ['dataExchange.request', 'public'],
    ['dataExchange.respond', 'public'],

    ['widget.register', 'widget:register'],
    ['widget.unregister', 'widget:register'],
    ['widget.listRegistered', 'widget:register'],
    ['widget.updateConfig', 'widget:register'],
    ['widget.instanceSettings.update', 'public'],
    ['widget.invalidate', 'public'],
    ['widget.invalidateTarget', 'storage:write'],

    ['tappList.list', 'tappList:read'],
    ['tappList.get', 'tappList:read'],
    ['tappList.getRecent', 'tappList:read'],
    ['tappList.getInstallPackage', 'tappList:read'],
    ['tappList.resolveStoreSource', 'tappList:read'],
    ['tappList.install', 'tappList:manage'],
    ['tappList.uninstall', 'tappList:manage'],
    ['tappList.start', 'tappList:manage'],
    ['tappList.stop', 'tappList:manage'],
    ['tappList.export', 'tappList:manage'],

    ['brewList.list', 'brew:read'],
    ['brewList.get', 'brew:read'],
    ['brewList.sources', 'brew:read'],
    ['brewList.categories', 'brew:read'],
    ['brewList.stats', 'brew:read'],
    ['brewList.discover', 'brew:manage'],
    ['brewList.exportOpml', 'brew:read'],

    ['brewList.markRead', 'brew:write'],
    ['brewList.markUnread', 'brew:write'],
    ['brewList.markAllRead', 'brew:write'],
    ['brewList.star', 'brew:write'],
    ['brewList.unstar', 'brew:write'],

    ['brewList.getComments', 'brew:read'],
    ['brewList.createComment', 'brew:commentWrite'],
    ['brewList.updateComment', 'brew:commentWrite'],
    ['brewList.deleteComment', 'brew:commentWrite'],
    ['brewList.getReplies', 'brew:read'],
    ['brewList.createReply', 'brew:commentWrite'],

    ['brewList.addSource', 'brew:manage'],
    ['brewList.updateSource', 'brew:manage'],
    ['brewList.deleteSource', 'brew:manage'],
    ['brewList.refreshSource', 'brew:manage'],
    ['brewList.importOpml', 'brew:manage'],
    ['brewList.createCategory', 'brew:manage'],
    ['brewList.deleteCategory', 'brew:manage'],

    ['platform.listEnabled', 'platform:read'],
    ['platform.getData', 'platform:read'],
    ['platform.getStats', 'platform:read'],
    ['platform.getDistribution', 'platform:read'],
    ['platform.addItem', 'platform:write'],
    ['platform.addItems', 'platform:write'],
    ['platform.registerPlatform', 'platform:register'],

    ['analytics.getSummary', 'analytics:read'],
    ['analytics.getVisitorCard', 'analytics:read'],
    // 输入/输出权限由请求形状决定，后端 Runtime Grant 强制。
    ['data.transform', 'public'],

    // 操作/上下文权限由后端动态解析。
    ['ai.tasks.create', 'public'],
    ['ai.tasks.get', 'public'],
    ['ai.tasks.cancel', 'public'],
    ['ai.tasks.usage', 'public'],
    ['ai.tasks.subscribe', 'public'],
    ['ai.tasks.unsubscribe', 'public'],

    ['model3d.status', '3d:generate'],
    ['model3d.upload', '3d:generate'],
    ['model3d.createTask', '3d:generate'],
    ['model3d.getTask', '3d:generate'],
    ['model3d.awaitTask', '3d:generate'],
    ['model3d.getUrl', 'public'],
    ['model3d.getMetadata', 'public'],

    ['report.platform.list', 'report:read'],
    ['report.platform.get', 'report:read'],
    ['report.platform.byPlatform', 'report:read'],
    ['report.create', 'report:write'],
    ['report.list', 'report:read'],
    ['report.get', 'report:read'],
    ['report.update', 'report:write'],
    ['report.delete', 'report:write'],

    // 四种 KV 共用 storage:read / storage:write；REST 另按命名空间做角色闸。
    // onChanged 是宿主事件，不进本表。
    ['storage.get', 'storage:read'],
    ['storage.set', 'storage:write'],
    ['storage.remove', 'storage:write'],
    ['storage.keys', 'storage:read'],
    ['storage.getAll', 'storage:read'],
    ['storage.clear', 'storage:write'],
    ['storage.usage', 'storage:read'],
    ['settings.get', 'storage:read'],
    ['settings.set', 'storage:write'],
    ['settings.getAll', 'storage:read'],
    ['shared.get', 'storage:read'],
    ['shared.set', 'storage:write'],
    ['shared.remove', 'storage:write'],
    ['shared.keys', 'storage:read'],
    ['shared.getAll', 'storage:read'],
    ['shared.clear', 'storage:write'],
    ['shared.usage', 'storage:read'],
    ['private.get', 'storage:read'],
    ['private.set', 'storage:write'],
    ['private.remove', 'storage:write'],
    ['private.keys', 'storage:read'],
    ['private.getAll', 'storage:read'],
    ['private.clear', 'storage:write'],
    ['private.usage', 'storage:read'],

    ['ui.showNotification', 'ui:notification'],
    ['ui.confirm', 'ui:confirm'],
    ['ui.openUrl', 'ui:openUrl'],
    ['ui.listOpenUrls', 'ui:openUrl'],
    ['ui.fullscreen.request', 'ui:fullscreen'],
    ['ui.fullscreen.exit', 'ui:fullscreen'],
    ['ui.fullscreen.toggle', 'ui:fullscreen'],
    ['ui.fullscreen.isFullscreen', 'ui:fullscreen'],

    ['media.control', 'media:control'],
    ['media.getStatus', 'media:read'],
    ['media.getPlaylist', 'media:read'],
    ['media.playTrack', 'media:control'],
    ['media.jumpToIndex', 'media:control'],
    ['media.getSpectrum', 'media:read'],
    // 宿主按帧推送；handler 仍校验 media:read。
    ['media.spectrumStream', 'media:read'],
    ['media.getLyrics', 'media:read'],
    ['media.getBeatGrid', 'media:read'],
    ['media.loadNeteasePlaylist', 'media:control'],
    ['media.getSkipVip', 'media:read'],
    ['media.setSkipVip', 'media:control'],

    ['component.registerTheme', 'component:theme'],
    ['component.registerAgent', 'component:agent'],
    // theme/agent 类型由后端动态校验。
    ['component.unregister', 'public'],

    ['shortcut.register', 'shortcut:register'],
    ['shortcut.unregister', 'shortcut:register'],

    ['event.publish', 'event:publish'],

    // Manifest 声明 + 交互状态 + schema + 接受方身份 + 宿主确认；后端强制。
    ['agent.v2.accept', 'public'],
    ['agent.v2.result', 'public'],
    ['agent.v2.reject', 'public'],
    ['agent.v2.intent', 'public'],

    ['background.require', 'event:subscribe'],
    ['background.release', 'event:subscribe'],

    ['dynamicContent.set', 'ui:notification'],
    ['dynamicContent.update', 'ui:notification'],
    ['dynamicContent.remove', 'ui:notification'],

    // 沙箱已持有的字节；不是 storage:read。iframe 无 allow-downloads。
    ['file.download', 'public'],

    ['assets.get', 'public'],
    ['assets.list', 'public'],

    ['scheduler.register', 'scheduler:register'],
    ['scheduler.unregister', 'scheduler:register'],
    ['scheduler.list', 'scheduler:register'],
    ['scheduler.get', 'scheduler:register'],
    ['scheduler.enable', 'scheduler:register'],
    ['scheduler.disable', 'scheduler:register'],
    ['scheduler.trigger', 'scheduler:register'],
    ['scheduler.subscribe', 'scheduler:register'],
    ['scheduler.unsubscribe', 'scheduler:register'],
    ['scheduler.complete', 'scheduler:register'],

    ['speech.tts', 'speech:tts'],
    ['speech.getVoices', 'speech:tts'],
    ['speech.getStatus', 'speech:tts'],
    ['speech.asr', 'speech:asr'],

    ['federation.getIdentity', 'federation:read'],
    ['federation.rotateKeys', 'federation:post'],
    ['federation.getFeed', 'federation:read'],
    ['federation.getRoomsFeed', 'federation:read'],
    ['federation.getTimeline', 'federation:read'],
    ['federation.getObject', 'federation:read'],
    ['federation.getFollowing', 'federation:read'],
    ['federation.getFollowers', 'federation:read'],
    ['federation.getPublished', 'federation:read'],
    ['federation.getChannels', 'federation:read'],
    ['federation.getChannel', 'federation:read'],
    ['federation.getMessages', 'federation:read'],
    ['federation.getRooms', 'federation:read'],
    ['federation.getRoom', 'federation:read'],
    ['federation.getRoomMembers', 'federation:read'],
    ['federation.getRoomMessages', 'federation:read'],
    ['federation.getRings', 'federation:read'],
    ['federation.getRing', 'federation:read'],
    ['federation.getRingPeers', 'federation:read'],
    ['federation.follow', 'federation:interact'],
    ['federation.unfollow', 'federation:interact'],
    ['federation.publish', 'federation:post'],
    ['federation.createNote', 'federation:post'],
    ['federation.like', 'federation:interact'],
    ['federation.unlike', 'federation:interact'],
    ['federation.bookmark', 'federation:interact'],
    ['federation.unbookmark', 'federation:interact'],
    ['federation.getBookmarks', 'federation:read'],
    ['federation.getExternalShareStatus', 'federation:read'],
    ['federation.composeExternalShare', 'federation:read'],
    ['federation.announce', 'federation:interact'],
    ['federation.unannounce', 'federation:interact'],
    ['federation.uploadMedia', 'federation:post'],
    ['federation.unpublish', 'federation:post'],
    ['federation.createChannel', 'federation:channel'],
    ['federation.acceptChannel', 'federation:channel'],
    ['federation.closeChannel', 'federation:channel'],
    ['federation.deleteChannel', 'federation:channel'],
    ['federation.createRoom', 'federation:room'],
    ['federation.updateRoom', 'federation:room'],
    ['federation.deleteRoom', 'federation:room'],
    ['federation.inviteMember', 'federation:room'],
    ['federation.acceptRoomInvite', 'federation:room'],
    ['federation.rejectRoomInvite', 'federation:room'],
    ['federation.removeMember', 'federation:room'],
    ['federation.setMemberRole', 'federation:room'],
    ['federation.leaveRoom', 'federation:room'],
    ['federation.transferRoomOwnership', 'federation:room'],
    ['federation.initiateChannelE2e', 'federation:channel'],
    ['federation.initiateRoomE2e', 'federation:room'],
    ['federation.addRoomSticker', 'federation:room'],
    ['federation.removeRoomSticker', 'federation:room'],
    ['federation.pinRoomMessage', 'federation:room'],
    ['federation.createRing', 'federation:ring'],
    ['federation.leaveRing', 'federation:ring'],
    ['federation.addPeer', 'federation:ring'],
    ['federation.removePeer', 'federation:ring'],
    ['federation.triggerSync', 'federation:ring'],
    ['federation.sendMessage', 'federation:message'],
    ['federation.sendRoomMessage', 'federation:message'],
    ['federation.subscribeChannel', 'federation:message'],
    ['federation.unsubscribeChannel', 'federation:message'],
    ['federation.subscribeRoom', 'federation:message'],
    ['federation.unsubscribeRoom', 'federation:message'],
    ['game.create', 'game:session'],
    ['game.join', 'game:session'],
    ['game.leave', 'game:session'],
    ['game.shareId', 'game:session'],
    ['game.sendIntent', 'game:session'],
    ['game.sendState', 'game:session'],
    ['federation.getTrustPolicy', 'federation:trust'],
    ['federation.updateTrustPolicy', 'federation:trust'],
    ['federation.getInstances', 'federation:trust'],
    ['federation.getDeliveryStats', 'federation:read'],
    ['federation.listDelivery', 'federation:read'],
    ['federation.retryDelivery', 'federation:post'],
    ['federation.cancelDelivery', 'federation:post'],
    ['federation.retryAllDeadDelivery', 'federation:post'],
    ['federation.cancelAllPendingDelivery', 'federation:post'],
    ['federation.dismissDelivery', 'federation:post'],
    ['federation.purgeDeadDelivery', 'federation:post'],
    ['federation.joinRoom', 'federation:room'],
    ['federation.updateInstanceTrust', 'federation:trust'],
    ['federation.toggleInstanceBlock', 'federation:trust'],
    ['federation.initiateTransfer', 'federation:files'],
    ['federation.listTransfers', 'federation:files'],
    ['federation.initiateRoomTransfer', 'federation:files'],
    ['federation.listRoomTransfers', 'federation:files'],
    ['federation.listRoomFiles', 'federation:files'],
    ['federation.getTransfer', 'federation:files'],
    ['federation.downloadTransfer', 'federation:files'],
    ['federation.uploadChunk', 'federation:files'],
    ['federation.cancelTransfer', 'federation:files'],
  ])
