[package]
name = "migration"
version = "0.3.25"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "lib.rs"

[dependencies]
sea-orm-migration = "2.0"

[dependencies.sea-orm]
version = "2.0"
features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
