[package]
name = "migration"
version = "0.5.1"
edition = "2024"
publish = false
license = "AGPL-3.0-only"

[lib]
name = "migration"
path = "lib.rs"

[dependencies]
myriad-phantasi = { path = "../../crates/myriad-phantasi" }
sea-orm-migration = { version = "2.0", default-features = false, features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }

[dependencies.sea-orm]
version = "2.0"
default-features = false
features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
]

[dependencies.serde_json]
version = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
