//! Configured image providers: OpenAI-compatible, OpenRouter, Volcengine Ark, Gemini.
//!
//! Resolution is chosen by the caller. Generated bytes are persisted into the
//! local image cache so Agent / Tapp surfaces get a stable `/api/...` URL
//! instead of a short-lived provider link or an inline data URL.

use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use flate2::read::GzDecoder;
use serde_json::{json, Map, Value};
use std::borrow::Cow;
use std::io::Read;
use std::time::Duration;

use crate::{
    config::DynamicConfig,
    services::{http_client::get_long_running_client, image_cache::ImageCacheService},
};

const MAX_PROMPT_CHARS: usize = 32_680;
const MAX_IMAGE_BYTES: usize = 10 * 1024 * 1024;
const MAX_PROVIDER_BODY_BYTES: usize = 64 * 1024 * 1024;
const GPT_IMAGE_2_MIN_PIXELS: u32 = 655_360;

#[derive(Clone, Debug)]
pub struct ImageGenerationConfig {
    pub provider: String,
    pub model: String,
    pub api_key: String,
    pub base_url: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedImage {
    pub source: String,
    pub media_type: String,
    pub width: u32,
    pub height: u32,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PersistedGeneratedImage {
    pub url: String,
    pub created: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImageReference {
    pub bytes: Vec<u8>,
    pub media_type: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ImageBackground {
    Opaque,
    Transparent,
}

impl ImageBackground {
    fn as_provider_value(self) -> &'static str {
        match self {
            Self::Opaque => "opaque",
            Self::Transparent => "transparent",
        }
    }
}

impl ImageReference {
    pub fn new(
        bytes: Vec<u8>,
        media_type: impl Into<String>,
    ) -> Result<Self, ImageGenerationError> {
        let media_type = media_type.into();
        validate_media_type(&media_type)?;
        validate_magic(&bytes, &media_type)?;
        Ok(Self { bytes, media_type })
    }

    fn data_url(&self) -> String {
        format!(
            "data:{};base64,{}",
            self.media_type,
            BASE64.encode(&self.bytes)
        )
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ImageGenerationError {
    NotConfigured(String),
    UnsupportedProvider(String),
    Provider(String),
    InvalidResponse(String),
}

impl std::fmt::Display for ImageGenerationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotConfigured(message)
            | Self::Provider(message)
            | Self::InvalidResponse(message) => formatter.write_str(message),
            Self::UnsupportedProvider(provider) => {
                write!(formatter, "unsupported image provider: {provider}")
            }
        }
    }
}

impl std::error::Error for ImageGenerationError {}

/// Stable code for UI + logs. Keep the Display message as the detail.
pub fn image_generation_failure_code(error: &ImageGenerationError) -> &'static str {
    match error {
        ImageGenerationError::NotConfigured(_) => "image_provider_unconfigured",
        ImageGenerationError::UnsupportedProvider(_) => "image_provider_unsupported",
        ImageGenerationError::InvalidResponse(_) => "image_provider_invalid_response",
        ImageGenerationError::Provider(message) => classify_provider_message(message),
    }
}

fn classify_provider_message(message: &str) -> &'static str {
    let lower = message.to_ascii_lowercase();
    if provider_status_is(&lower, 402)
        || lower.contains("insufficient")
        || lower.contains("payment required")
        || lower.contains("credit")
        || lower.contains("balance")
        || lower.contains("quota")
    {
        return "image_provider_credits";
    }
    if provider_status_is(&lower, 401)
        || provider_status_is(&lower, 403)
        || lower.contains("unauthorized")
        || lower.contains("invalid api key")
        || lower.contains("invalid_api_key")
    {
        return "image_provider_unauthorized";
    }
    if provider_status_is(&lower, 429)
        || lower.contains("rate limit")
        || lower.contains("rate-limit")
    {
        return "image_provider_rate_limited";
    }
    if provider_status_is(&lower, 400) || provider_status_is(&lower, 422) {
        return "image_provider_rejected";
    }
    "portrait_generation_failed"
}

fn provider_status_is(lower: &str, status: u16) -> bool {
    lower.contains(&format!("http {status}"))
}

pub fn config_from_dynamic(
    dynamic: &DynamicConfig,
) -> Result<ImageGenerationConfig, ImageGenerationError> {
    let source = dynamic.find_vendor_source(&dynamic.ai_image_source);
    let provider = source
        .as_ref()
        .map(|item| image_protocol(&item.kind))
        .filter(|item| !item.is_empty())
        .unwrap_or_else(|| image_protocol(&dynamic.ai_image_provider));
    if provider.is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image provider is not configured".to_string(),
        ));
    }
    let (api_key, base_url) = if let Some(source) = source.as_ref() {
        match source.kind.trim().to_ascii_lowercase().as_str() {
            "openai" | "openai_compatible" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_openai_api_key()),
                if source.base_url.trim().is_empty() {
                    dynamic.shared_openai_base_url()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "openrouter" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_openrouter_api_key()),
                if source.base_url.trim().is_empty() {
                    "https://openrouter.ai/api/v1".to_string()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "volcengine" | "ark" | "seedream" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_volcengine_api_key()),
                if source.base_url.trim().is_empty() {
                    dynamic.shared_volcengine_base_url()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "gemini" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_gemini_api_key()),
                gemini_image_base_url(dynamic, Some(source)),
            ),
            other => return Err(ImageGenerationError::UnsupportedProvider(other.to_string())),
        }
    } else {
        match provider.as_str() {
            "openai" => (
                dynamic.shared_openai_api_key(),
                dynamic.shared_openai_base_url(),
            ),
            "openrouter" => (
                dynamic.shared_openrouter_api_key(),
                "https://openrouter.ai/api/v1".to_string(),
            ),
            "volcengine" | "ark" | "seedream" => (
                dynamic.shared_volcengine_api_key(),
                dynamic.shared_volcengine_base_url(),
            ),
            "gemini" => (
                dynamic.shared_gemini_api_key(),
                gemini_image_base_url(dynamic, None),
            ),
            other => return Err(ImageGenerationError::UnsupportedProvider(other.to_string())),
        }
    };
    let api_key = api_key.ok_or_else(|| {
        ImageGenerationError::NotConfigured(format!(
            "{} image API key is not configured",
            provider_label(&provider)
        ))
    })?;
    if dynamic.ai_image_model.trim().is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image model is not configured".to_string(),
        ));
    }
    if base_url.is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image provider base URL is not configured".to_string(),
        ));
    }
    Ok(ImageGenerationConfig {
        provider,
        model: dynamic.ai_image_model.trim().to_string(),
        api_key: api_key.to_string(),
        base_url: base_url.trim_end_matches('/').to_string(),
    })
}

pub async fn generate_image(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    reference: Option<&ImageReference>,
) -> Result<GeneratedImage, ImageGenerationError> {
    generate_image_with_background(config, prompt, width, height, reference, None).await
}

pub async fn generate_image_with_background(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    reference: Option<&ImageReference>,
    background: Option<ImageBackground>,
) -> Result<GeneratedImage, ImageGenerationError> {
    generate_image_with_references(
        config,
        prompt,
        width,
        height,
        reference.map(std::slice::from_ref).unwrap_or_default(),
        background,
    )
    .await
}

pub async fn generate_image_with_references(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    references: &[ImageReference],
    background: Option<ImageBackground>,
) -> Result<GeneratedImage, ImageGenerationError> {
    let prompt = prompt.trim();
    if prompt.is_empty() || prompt.chars().count() > MAX_PROMPT_CHARS {
        return Err(ImageGenerationError::Provider(format!(
            "image prompt must contain 1 to {MAX_PROMPT_CHARS} characters"
        )));
    }
    let width = width.clamp(256, 2048);
    let height = height.clamp(256, 2048);
    let result =
        generate_image_provider(config, prompt, width, height, references, background).await;
    let (input_tokens, output_tokens) =
        crate::services::ai_cost_ledger::estimate_image_tokens(prompt, width, height);
    let error_code = result.as_ref().err().map(image_generation_failure_code);
    crate::services::ai_cost_ledger::record_ai_tokens_from_attribution(
        &config.provider,
        &config.model,
        input_tokens,
        output_tokens,
        if result.is_ok() {
            "completed"
        } else {
            "failed"
        },
        error_code,
    )
    .await;
    if let Err(error) = &result {
        tracing::error!(
            provider = %config.provider,
            model = %config.model,
            width,
            height,
            code = image_generation_failure_code(error),
            %error,
            "image generation failed"
        );
    }
    result
}

async fn generate_image_provider(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    references: &[ImageReference],
    background: Option<ImageBackground>,
) -> Result<GeneratedImage, ImageGenerationError> {
    if config.provider == "gemini" {
        return crate::services::gemini_media::generate_image(
            config, prompt, width, height, references,
        )
        .await;
    }
    let client = get_long_running_client().await;
    let response = if config.provider == "openai" {
        if !references.is_empty() {
            let endpoint = format!("{}/images/edits", config.base_url);
            let form = image_edit_form(config, prompt, width, height, references, background)?;
            apply_image_headers(client.post(endpoint).bearer_auth(&config.api_key))
                .multipart(form)
                .send()
                .await
        } else {
            let (endpoint, body) =
                request_parts_with_background(config, prompt, width, height, &[], background)?;
            apply_image_headers(client.post(endpoint).bearer_auth(&config.api_key))
                .json(&body)
                .send()
                .await
        }
    } else {
        let reference_data_urls: Vec<String> =
            references.iter().map(ImageReference::data_url).collect();
        let (endpoint, body) = request_parts_with_background(
            config,
            prompt,
            width,
            height,
            &reference_data_urls
                .iter()
                .map(String::as_str)
                .collect::<Vec<_>>(),
            background,
        )?;
        apply_image_headers(client.post(endpoint).bearer_auth(&config.api_key))
            .json(&body)
            .send()
            .await
    }
    .map_err(|error| ImageGenerationError::Provider(display_error(&error)))?;
    read_image_api_response(response, &config.provider, width, height).await
}

fn image_edit_form(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    references: &[ImageReference],
    background: Option<ImageBackground>,
) -> Result<reqwest::multipart::Form, ImageGenerationError> {
    let options = request_options(config, background);
    let mut form = reqwest::multipart::Form::new()
        .text("model", strip_openai_prefix(&config.model).to_string())
        .text("prompt", prompt.to_string())
        .text("size", image_size_param(config, width, height));
    // Only these GPT Image models expose configurable input fidelity.
    if matches!(
        strip_openai_prefix(&config.model),
        "gpt-image-1" | "gpt-image-1.5"
    ) {
        form = form.text("input_fidelity", "high");
    }
    if options.include_n {
        form = form.text("n", "1");
    }
    if let Some(background) = options.background {
        form = form.text("background", background);
    }
    if let Some(output_format) = options.output_format {
        form = form.text("output_format", output_format);
    }
    if let Some(quality) = options.quality {
        form = form.text("quality", quality);
    }
    let field = if references.len() == 1 {
        "image"
    } else {
        "image[]"
    };
    for reference in references {
        let part = reqwest::multipart::Part::bytes(reference.bytes.clone())
            .file_name(reference_file_name(&reference.media_type))
            .mime_str(&reference.media_type)
            .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
        form = form.part(field, part);
    }
    Ok(form)
}

/// Load a reference from the site's image cache without an outbound request.
pub async fn load_local_reference(url: &str) -> Result<ImageReference, ImageGenerationError> {
    let (bytes, media_type) = ImageCacheService::new()
        .read_local_public_url(url)
        .await
        .map_err(ImageGenerationError::Provider)?;
    ImageReference::new(bytes, media_type)
}

pub async fn persist_generated(generated: &GeneratedImage) -> Result<String, ImageGenerationError> {
    Ok(persist_generated_with_status(generated).await?.url)
}

pub async fn persist_generated_with_status(
    generated: &GeneratedImage,
) -> Result<PersistedGeneratedImage, ImageGenerationError> {
    let (bytes, media_type) = load_generated_bytes(generated).await?;
    let stored = ImageCacheService::new()
        .store_bytes_with_status(&bytes, &media_type)
        .await
        .map_err(ImageGenerationError::Provider)?;
    Ok(PersistedGeneratedImage {
        url: stored.url,
        created: stored.created,
    })
}

pub async fn remove_persisted_generated(
    persisted: &PersistedGeneratedImage,
) -> Result<(), ImageGenerationError> {
    if !persisted.created {
        return Ok(());
    }
    ImageCacheService::new()
        .remove_stored_url(&persisted.url)
        .await
        .map_err(ImageGenerationError::Provider)
}

pub(crate) async fn load_generated_bytes(
    generated: &GeneratedImage,
) -> Result<(Vec<u8>, String), ImageGenerationError> {
    if let Some(data) = generated.source.strip_prefix("data:") {
        let (metadata, encoded) = data.split_once(',').ok_or_else(|| {
            ImageGenerationError::InvalidResponse("invalid image data URL".to_string())
        })?;
        if !metadata.ends_with(";base64") {
            return Err(ImageGenerationError::InvalidResponse(
                "image data URL is not base64 encoded".to_string(),
            ));
        }
        let media_type = metadata.trim_end_matches(";base64");
        validate_media_type(media_type)?;
        let bytes = BASE64.decode(encoded).map_err(|_| {
            ImageGenerationError::InvalidResponse("invalid image base64".to_string())
        })?;
        if bytes.len() > MAX_IMAGE_BYTES {
            return Err(ImageGenerationError::InvalidResponse(
                "generated image exceeds storage limit".to_string(),
            ));
        }
        validate_magic(&bytes, media_type)?;
        return Ok((bytes, media_type.to_string()));
    }

    let (url, client) = crate::services::outbound_security::build_public_http_client(
        &generated.source,
        Duration::from_secs(5 * 60),
        Some("Myriad-ImageGeneration/1.0"),
    )
    .await
    .map_err(ImageGenerationError::InvalidResponse)?;
    let response = client
        .get(url)
        .send()
        .await
        .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
    if !response.status().is_success() {
        return Err(ImageGenerationError::Provider(format!(
            "generated image download returned HTTP {}",
            response.status()
        )));
    }
    if response.content_length().unwrap_or(0) > MAX_IMAGE_BYTES as u64 {
        return Err(ImageGenerationError::InvalidResponse(
            "generated image exceeds storage limit".to_string(),
        ));
    }
    let media_type = response
        .headers()
        .get(reqwest::header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.split(';').next())
        .unwrap_or(&generated.media_type)
        .to_string();
    validate_media_type(&media_type)?;
    let bytes = response
        .bytes()
        .await
        .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
    if bytes.len() > MAX_IMAGE_BYTES {
        return Err(ImageGenerationError::InvalidResponse(
            "generated image exceeds storage limit".to_string(),
        ));
    }
    validate_magic(&bytes, &media_type)?;
    Ok((bytes.to_vec(), media_type))
}

fn request_parts_with_background(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    reference_data_urls: &[&str],
    background: Option<ImageBackground>,
) -> Result<(String, Value), ImageGenerationError> {
    let size = format!("{width}x{height}");
    let options = request_options(config, background);
    match config.provider.as_str() {
        "openai" => {
            if !reference_data_urls.is_empty() {
                return Err(ImageGenerationError::Provider(
                    "OpenAI image references require the image edits endpoint".to_string(),
                ));
            }
            let mut body = json!({
                "model": strip_openai_prefix(&config.model),
                "prompt": prompt,
                "size": image_size_param(config, width, height)
            });
            if options.include_n {
                body["n"] = json!(1);
            }
            apply_background_options(&mut body, options);
            if is_gpt_image_model(&config.model) {
                // Keep the JSON envelope; streaming replies as SSE, which the old
                // `response.json()` path reported only as "error decoding response body".
                body["stream"] = json!(false);
            }
            Ok((format!("{}/images/generations", config.base_url), body))
        }
        "openrouter" => {
            let mut body = json!({
                "model": config.model,
                "prompt": prompt,
                "aspect_ratio": aspect_ratio(width, height)
            });
            if options.include_n {
                body["n"] = json!(1);
            }
            apply_background_options(&mut body, options);
            if !reference_data_urls.is_empty() {
                body["input_references"] = json!(reference_data_urls
                    .iter()
                    .map(|reference| json!({
                        "type": "image_url",
                        "image_url": { "url": reference }
                    }))
                    .collect::<Vec<_>>());
            }
            Ok((format!("{}/images", config.base_url), body))
        }
        "volcengine" | "ark" | "seedream" => {
            let mut body = Map::new();
            body.insert("model".to_string(), json!(config.model));
            body.insert("prompt".to_string(), json!(prompt));
            body.insert("size".to_string(), json!(size));
            body.insert("response_format".to_string(), json!("url"));
            body.insert("sequential_image_generation".to_string(), json!("disabled"));
            body.insert("watermark".to_string(), json!(false));
            body.insert("stream".to_string(), json!(false));
            if !reference_data_urls.is_empty() {
                body.insert("image".to_string(), json!(reference_data_urls));
            }
            Ok((
                format!("{}/images/generations", config.base_url),
                Value::Object(body),
            ))
        }
        other => Err(ImageGenerationError::UnsupportedProvider(other.to_string())),
    }
}

#[derive(Clone, Copy)]
struct ImageRequestOptions {
    background: Option<&'static str>,
    output_format: Option<&'static str>,
    include_n: bool,
    quality: Option<&'static str>,
}

fn request_options(
    config: &ImageGenerationConfig,
    background: Option<ImageBackground>,
) -> ImageRequestOptions {
    if config.provider == "openrouter" {
        let native_background = supports_background_option(&config.model);
        return ImageRequestOptions {
            background: native_background.then(|| {
                background
                    .unwrap_or_else(|| default_background(&config.model))
                    .as_provider_value()
            }),
            output_format: None,
            include_n: false,
            quality: gpt_image_quality(&config.model),
        };
    }
    if is_gpt_image_2(&config.model) {
        return ImageRequestOptions {
            background: Some(
                background
                    .unwrap_or(ImageBackground::Opaque)
                    .as_provider_value(),
            ),
            output_format: None,
            include_n: true,
            quality: gpt_image_quality(&config.model),
        };
    }
    if is_gpt_image_1(&config.model) {
        return ImageRequestOptions {
            background: supports_background_option(&config.model).then(|| {
                background
                    .unwrap_or_else(|| default_background(&config.model))
                    .as_provider_value()
            }),
            output_format: supports_background_option(&config.model).then_some("png"),
            include_n: true,
            quality: gpt_image_quality(&config.model),
        };
    }
    ImageRequestOptions {
        background: None,
        output_format: None,
        include_n: true,
        quality: None,
    }
}

fn is_gpt_image_2(model: &str) -> bool {
    let model = strip_openai_prefix(model).to_ascii_lowercase();
    model == "gpt-image-2" || model.starts_with("gpt-image-2-")
}

fn is_gpt_image_1(model: &str) -> bool {
    matches!(
        strip_openai_prefix(model).to_ascii_lowercase().as_str(),
        "gpt-image-1" | "gpt-image-1-mini" | "gpt-image-1.5"
    )
}

fn is_gpt_image_1_mini(model: &str) -> bool {
    strip_openai_prefix(model).eq_ignore_ascii_case("gpt-image-1-mini")
}

fn supports_background_option(model: &str) -> bool {
    is_gpt_image_2(model) || (is_gpt_image_1(model) && !is_gpt_image_1_mini(model))
}

fn default_background(model: &str) -> ImageBackground {
    if is_gpt_image_2(model) {
        ImageBackground::Opaque
    } else {
        ImageBackground::Transparent
    }
}

fn is_gpt_image_model(model: &str) -> bool {
    is_gpt_image_1(model) || is_gpt_image_2(model)
}

fn image_size_param(config: &ImageGenerationConfig, width: u32, height: u32) -> String {
    if is_gpt_image_1(&config.model) {
        return if width == height {
            "1024x1024".to_string()
        } else if width < height {
            "1024x1536".to_string()
        } else {
            "1536x1024".to_string()
        };
    }

    if !is_gpt_image_2(&config.model) {
        return format!("{width}x{height}");
    }
    let width = snap_multiple(width, 16).clamp(16, 3840);
    let height = snap_multiple(height, 16).clamp(16, 3840);
    if width.saturating_mul(height) < GPT_IMAGE_2_MIN_PIXELS {
        return "1024x1024".to_string();
    }
    format!("{width}x{height}")
}

fn snap_multiple(value: u32, multiple: u32) -> u32 {
    if multiple == 0 {
        return value;
    }
    let rounded = value
        .saturating_add(multiple / 2)
        .saturating_div(multiple)
        .saturating_mul(multiple);
    rounded.max(multiple)
}

fn apply_background_options(body: &mut Value, options: ImageRequestOptions) {
    if let Some(background) = options.background {
        body["background"] = json!(background);
    }
    if let Some(output_format) = options.output_format {
        body["output_format"] = json!(output_format);
    }
    if let Some(quality) = options.quality {
        body["quality"] = json!(quality);
    }
}

fn gpt_image_quality(model: &str) -> Option<&'static str> {
    is_gpt_image_model(model).then_some("high")
}

fn aspect_ratio(width: u32, height: u32) -> &'static str {
    if width == height {
        "1:1"
    } else if width.saturating_mul(2) == height.saturating_mul(3) {
        "3:2"
    } else if width.saturating_mul(3) == height.saturating_mul(2) {
        "2:3"
    } else if width.saturating_mul(3) == height.saturating_mul(4) {
        "4:3"
    } else if width.saturating_mul(4) == height.saturating_mul(3) {
        "3:4"
    } else if width > height {
        "16:9"
    } else {
        "9:16"
    }
}

fn reference_file_name(media_type: &str) -> &'static str {
    match media_type {
        "image/jpeg" => "character-reference.jpg",
        "image/webp" => "character-reference.webp",
        _ => "character-reference.png",
    }
}

fn apply_image_headers(request: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
    request.header(reqwest::header::ACCEPT, "application/json")
}

fn display_error(error: &dyn std::error::Error) -> String {
    let mut message = error.to_string();
    let mut current = error.source();
    while let Some(source) = current {
        let piece = source.to_string();
        if !piece.is_empty() && !message.contains(&piece) {
            message.push_str(": ");
            message.push_str(&piece);
        }
        current = source.source();
    }
    message
}

async fn read_image_api_response(
    response: reqwest::Response,
    provider: &str,
    width: u32,
    height: u32,
) -> Result<GeneratedImage, ImageGenerationError> {
    let status = response.status();
    let content_type = header_value(response.headers(), reqwest::header::CONTENT_TYPE);
    let content_encoding = header_value(response.headers(), reqwest::header::CONTENT_ENCODING);
    let bytes = response
        .bytes()
        .await
        .map_err(|error| ImageGenerationError::InvalidResponse(display_error(&error)))?;
    if bytes.len() > MAX_PROVIDER_BODY_BYTES {
        return Err(ImageGenerationError::InvalidResponse(
            "image provider response exceeds size limit".to_string(),
        ));
    }
    if !status.is_success() {
        let body = String::from_utf8_lossy(&bytes);
        let body: String = body.chars().take(600).collect();
        return Err(ImageGenerationError::Provider(format!(
            "{} image API returned HTTP {status}: {body}",
            provider_label(provider)
        )));
    }
    let body = decompress_provider_body(&bytes, content_encoding.as_deref())?;
    if let Some(image) = parse_raw_image(&body, width, height)? {
        return Ok(image);
    }
    let value = decode_provider_body(&body, content_type.as_deref())?;
    parse_image_response(&value, width, height)
}

fn header_value(
    headers: &reqwest::header::HeaderMap,
    name: reqwest::header::HeaderName,
) -> Option<String> {
    headers
        .get(name)
        .and_then(|value| value.to_str().ok())
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
}

fn decompress_provider_body<'a>(
    bytes: &'a [u8],
    content_encoding: Option<&str>,
) -> Result<Cow<'a, [u8]>, ImageGenerationError> {
    if bytes.starts_with(&[0x1f, 0x8b]) {
        return Ok(Cow::Owned(gzip_decode(bytes)?));
    }
    let encoding = content_encoding.unwrap_or("").to_ascii_lowercase();
    if encoding.contains("gzip") {
        tracing::warn!(
            content_encoding,
            "image provider advertised gzip without gzip magic; parsing the body as-is"
        );
    }
    Ok(Cow::Borrowed(bytes))
}

fn gzip_decode(bytes: &[u8]) -> Result<Vec<u8>, ImageGenerationError> {
    let mut decoder = GzDecoder::new(bytes);
    let mut out = Vec::new();
    let mut buf = [0u8; 8192];
    loop {
        let read = decoder.read(&mut buf).map_err(|error| {
            ImageGenerationError::InvalidResponse(format!(
                "error decoding gzip response body: {error}"
            ))
        })?;
        if read == 0 {
            break;
        }
        if out.len().saturating_add(read) > MAX_PROVIDER_BODY_BYTES {
            return Err(ImageGenerationError::InvalidResponse(
                "image provider response exceeds size limit".to_string(),
            ));
        }
        out.extend_from_slice(&buf[..read]);
    }
    Ok(out)
}

fn decode_provider_body(
    bytes: &[u8],
    content_type: Option<&str>,
) -> Result<Value, ImageGenerationError> {
    let bytes = bytes.strip_prefix(&[0xEF, 0xBB, 0xBF]).unwrap_or(bytes);
    if bytes.is_empty() {
        return Err(ImageGenerationError::InvalidResponse(
            "image provider returned an empty body".to_string(),
        ));
    }
    match serde_json::from_slice::<Value>(bytes) {
        Ok(value) => Ok(value),
        Err(error) => {
            if let Ok(text) = std::str::from_utf8(bytes) {
                if looks_like_sse(content_type, text) {
                    if let Some(value) = parse_sse_image_event(text) {
                        return Ok(value);
                    }
                }
            }
            Err(ImageGenerationError::InvalidResponse(format!(
                "error decoding response body: {error} (content-type {}, {})",
                content_type.unwrap_or("missing"),
                body_preview(bytes)
            )))
        }
    }
}

fn looks_like_sse(content_type: Option<&str>, text: &str) -> bool {
    content_type.is_some_and(|value| value.to_ascii_lowercase().contains("text/event-stream"))
        || text.starts_with("event:")
        || text.starts_with("data:")
}

fn parse_sse_image_event(text: &str) -> Option<Value> {
    let mut completed = None;
    let mut last_with_image = None;
    let mut data_lines = Vec::new();
    for line in text.lines().chain(std::iter::once("")) {
        if let Some(rest) = line.strip_prefix("data:") {
            data_lines.push(rest.trim().to_string());
            continue;
        }
        if !line.is_empty() {
            continue;
        }
        if data_lines.is_empty() {
            continue;
        }
        let joined = data_lines.join("\n");
        data_lines.clear();
        if joined.is_empty() || joined == "[DONE]" {
            continue;
        }
        let Ok(value) = serde_json::from_str::<Value>(&joined) else {
            continue;
        };
        if image_payload_from_value(&value).is_none() {
            continue;
        }
        if value.get("type").and_then(Value::as_str) == Some("image_generation.completed") {
            completed = Some(value);
        } else {
            last_with_image = Some(value);
        }
    }
    completed.or(last_with_image)
}

fn parse_raw_image(
    bytes: &[u8],
    width: u32,
    height: u32,
) -> Result<Option<GeneratedImage>, ImageGenerationError> {
    let media_type = if bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
        "image/png"
    } else if bytes.starts_with(&[0xff, 0xd8, 0xff]) {
        "image/jpeg"
    } else if bytes.starts_with(b"RIFF") && bytes.get(8..12) == Some(b"WEBP") {
        "image/webp"
    } else {
        return Ok(None);
    };
    if bytes.len() > MAX_IMAGE_BYTES {
        return Err(ImageGenerationError::InvalidResponse(
            "generated image exceeds storage limit".to_string(),
        ));
    }
    Ok(Some(GeneratedImage {
        source: format!("data:{media_type};base64,{}", BASE64.encode(bytes)),
        media_type: media_type.to_string(),
        width,
        height,
    }))
}

fn body_preview(bytes: &[u8]) -> String {
    let take = bytes.len().min(12);
    match std::str::from_utf8(&bytes[..bytes.len().min(80)]) {
        Ok(text) => format!("starts {:?}", text.chars().take(48).collect::<String>()),
        Err(_) => format!(
            "binary {} bytes, starts {:02x?}",
            bytes.len(),
            &bytes[..take]
        ),
    }
}

fn parse_image_response(
    value: &Value,
    width: u32,
    height: u32,
) -> Result<GeneratedImage, ImageGenerationError> {
    let fallback_media_type = media_type_from_output_format(value).unwrap_or("image/png");
    let item = value
        .get("data")
        .and_then(Value::as_array)
        .and_then(|items| items.first())
        .or_else(|| {
            value
                .get("output")
                .and_then(Value::as_array)
                .and_then(|items| {
                    items
                        .iter()
                        .find(|item| image_payload_from_value(item).is_some())
                })
        })
        .unwrap_or(value);
    let Some(source) = image_payload_from_value(item).or_else(|| image_payload_from_value(value))
    else {
        return Err(ImageGenerationError::InvalidResponse(
            "response contained no image data".to_string(),
        ));
    };
    let media_type = item
        .get("media_type")
        .and_then(Value::as_str)
        .or_else(|| media_type_from_output_format(item))
        .or(Some(fallback_media_type))
        .unwrap_or("image/png")
        .to_string();
    let source = match source {
        ImagePayload::Base64(encoded) => format!("data:{media_type};base64,{encoded}"),
        ImagePayload::Url(url) => url.to_string(),
    };
    let (width, height) = size_from_value(item)
        .or_else(|| size_from_value(value))
        .unwrap_or((width, height));
    Ok(GeneratedImage {
        source,
        media_type,
        width,
        height,
    })
}

enum ImagePayload<'a> {
    Base64(&'a str),
    Url(&'a str),
}

fn image_payload_from_value(value: &Value) -> Option<ImagePayload<'_>> {
    value
        .get("b64_json")
        .and_then(Value::as_str)
        .or_else(|| value.get("result").and_then(Value::as_str))
        .map(ImagePayload::Base64)
        .or_else(|| {
            value
                .get("url")
                .and_then(Value::as_str)
                .map(ImagePayload::Url)
        })
}

fn media_type_from_output_format(value: &Value) -> Option<&'static str> {
    match value.get("output_format").and_then(Value::as_str)? {
        "png" => Some("image/png"),
        "jpeg" | "jpg" => Some("image/jpeg"),
        "webp" => Some("image/webp"),
        _ => None,
    }
}

fn size_from_value(value: &Value) -> Option<(u32, u32)> {
    value
        .get("size")
        .and_then(Value::as_str)
        .and_then(|size| size.split_once('x'))
        .and_then(|(width, height)| Some((width.parse().ok()?, height.parse().ok()?)))
}

fn validate_media_type(media_type: &str) -> Result<(), ImageGenerationError> {
    if matches!(media_type, "image/png" | "image/jpeg" | "image/webp") {
        Ok(())
    } else {
        Err(ImageGenerationError::InvalidResponse(format!(
            "unsupported generated image media type: {media_type}"
        )))
    }
}

fn validate_magic(bytes: &[u8], media_type: &str) -> Result<(), ImageGenerationError> {
    let valid = match media_type {
        "image/png" => bytes.starts_with(b"\x89PNG\r\n\x1a\n"),
        "image/jpeg" => bytes.starts_with(&[0xff, 0xd8, 0xff]),
        "image/webp" => bytes.starts_with(b"RIFF") && bytes.get(8..12) == Some(b"WEBP"),
        _ => false,
    };
    valid.then_some(()).ok_or_else(|| {
        ImageGenerationError::InvalidResponse(
            "generated payload does not match its image media type".to_string(),
        )
    })
}

fn strip_openai_prefix(model: &str) -> &str {
    model.strip_prefix("openai/").unwrap_or(model)
}

fn image_protocol(kind: &str) -> String {
    match kind.trim().to_ascii_lowercase().as_str() {
        "gemini" => "gemini".to_string(),
        "volcengine" | "ark" | "seedream" => "volcengine".to_string(),
        "openrouter" => "openrouter".to_string(),
        "openai" | "openai_compatible" => "openai".to_string(),
        other => other.to_string(),
    }
}

fn gemini_image_base_url(
    dynamic: &DynamicConfig,
    source: Option<&crate::config::AiVendorSource>,
) -> String {
    if let Some(source) = source {
        let custom = source.base_url.trim();
        if !custom.is_empty() {
            return custom.trim_end_matches('/').to_string();
        }
    }
    dynamic
        .gemini_base_url
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("https://generativelanguage.googleapis.com")
        .trim_end_matches('/')
        .to_string()
}

fn provider_label(provider: &str) -> &str {
    match provider {
        "openai" => "OpenAI",
        "openrouter" => "OpenRouter",
        "volcengine" | "ark" | "seedream" => "Volcengine Ark",
        "gemini" => "Gemini",
        _ => provider,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DynamicConfig;
    #[test]
    fn builds_each_supported_provider_request() {
        for (provider, expected_suffix) in [
            ("openai", "/images/generations"),
            ("openrouter", "/images"),
            ("volcengine", "/images/generations"),
        ] {
            let config = ImageGenerationConfig {
                provider: provider.to_string(),
                model: "model".to_string(),
                api_key: "secret".to_string(),
                base_url: "https://example.com/v1".to_string(),
            };
            let (endpoint, body) =
                request_parts_with_background(&config, "portrait", 1024, 1024, &[], None).unwrap();
            assert!(endpoint.ends_with(expected_suffix));
            assert_eq!(body["model"], "model");
            assert_eq!(body["prompt"], "portrait");
        }
    }

    #[test]
    fn compatible_image_models_omit_openai_only_fields() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "Kwai-Kolors/Kolors".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.siliconflow.cn/v1".to_string(),
        };
        let (_, body) =
            request_parts_with_background(&config, "portrait", 1024, 1024, &[], None).unwrap();
        assert_eq!(body["model"], "Kwai-Kolors/Kolors");
        assert_eq!(body["size"], "1024x1024");
        assert_eq!(body["n"], 1);
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
        assert!(body.get("quality").is_none());
        assert!(body.get("stream").is_none());
    }

    #[test]
    fn gpt_image_2_uses_supported_background_contract() {
        let config = ImageGenerationConfig {
            provider: "openrouter".to_string(),
            model: "openai/gpt-image-2".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://openrouter.ai/api/v1".to_string(),
        };
        let reference = "data:image/png;base64,AA==";
        let (_, body) =
            request_parts_with_background(&config, "portrait", 1152, 1536, &[reference], None)
                .unwrap();
        assert_eq!(body["background"], "opaque");
        assert_eq!(body["quality"], "high");
        assert!(body.get("output_format").is_none());
        assert!(body.get("n").is_none());
        assert_eq!(body["aspect_ratio"], "3:4");
        assert_eq!(body["input_references"][0]["image_url"]["url"], reference);
    }

    #[test]
    fn openrouter_only_sends_optional_parameters_known_to_be_supported() {
        let generic = ImageGenerationConfig {
            provider: "openrouter".to_string(),
            model: "qwen/qwen-image-3".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://openrouter.ai/api/v1".to_string(),
        };
        let (_, body) =
            request_parts_with_background(&generic, "portrait", 1536, 1024, &[], None).unwrap();
        assert_eq!(body["aspect_ratio"], "3:2");
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
        assert!(body.get("n").is_none());

        let (_, portrait) =
            request_parts_with_background(&generic, "portrait", 1152, 1536, &[], None).unwrap();
        assert_eq!(portrait["aspect_ratio"], "3:4");

        let transparent = ImageGenerationConfig {
            model: "openai/gpt-image-1".to_string(),
            ..generic
        };
        let (_, body) =
            request_parts_with_background(&transparent, "portrait", 1024, 1024, &[], None).unwrap();
        assert_eq!(body["background"], "transparent");
        assert!(body.get("output_format").is_none());
    }

    #[test]
    fn portrait_background_can_override_gpt_image_transparency_default() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "gpt-image-1".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.openai.com/v1".to_string(),
        };
        let (_, body) = request_parts_with_background(
            &config,
            "portrait",
            1152,
            1536,
            &[],
            Some(ImageBackground::Opaque),
        )
        .unwrap();
        assert_eq!(body["background"], "opaque");
        assert_eq!(body["output_format"], "png");
        assert_eq!(body["quality"], "high");
        assert_eq!(body["size"], "1024x1536");
    }

    #[test]
    fn gpt_image_1_mini_omits_unsupported_background_and_uses_fixed_size() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "gpt-image-1-mini".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.openai.com/v1".to_string(),
        };
        let (_, body) = request_parts_with_background(
            &config,
            "portrait",
            1152,
            1536,
            &[],
            Some(ImageBackground::Opaque),
        )
        .unwrap();
        assert_eq!(body["size"], "1024x1536");
        assert_eq!(body["quality"], "high");
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
    }

    #[test]
    fn reference_requests_use_provider_native_contracts() {
        let reference = "data:image/png;base64,AA==";
        for (provider, key) in [("openrouter", "input_references"), ("volcengine", "image")] {
            let config = ImageGenerationConfig {
                provider: provider.to_string(),
                model: "model".to_string(),
                api_key: "secret".to_string(),
                base_url: "https://example.com/v1".to_string(),
            };
            let (_, body) = request_parts_with_background(
                &config,
                "turn around",
                1024,
                1024,
                &[reference],
                None,
            )
            .unwrap();
            assert!(body.get(key).is_some());
        }
    }

    #[test]
    fn image_reference_rejects_spoofed_media_type() {
        assert!(ImageReference::new(b"not png".to_vec(), "image/png").is_err());
    }

    #[test]
    fn json_providers_keep_all_references_in_order() {
        let references = [
            "data:image/png;base64,first",
            "data:image/jpeg;base64,second",
        ];
        for provider in ["openrouter", "volcengine", "ark", "seedream"] {
            let config = ImageGenerationConfig {
                provider: provider.into(),
                model: "model".into(),
                api_key: "secret".into(),
                base_url: "https://example.com/v1".into(),
            };
            let (_, body) =
                request_parts_with_background(&config, "combine", 1024, 1024, &references, None)
                    .unwrap();
            if provider == "openrouter" {
                assert_eq!(body["input_references"].as_array().unwrap().len(), 2);
                for (index, reference) in references.iter().enumerate() {
                    assert_eq!(
                        body["input_references"][index]["image_url"]["url"],
                        *reference
                    );
                }
            } else {
                assert_eq!(body["image"], json!(references));
            }
            let (_, text_only) =
                request_parts_with_background(&config, "draw", 1024, 1024, &[], None).unwrap();
            assert!(text_only.get("image").is_none());
            assert!(text_only.get("input_references").is_none());
        }
    }

    #[tokio::test]
    async fn openai_edit_multipart_preserves_single_and_multiple_references() {
        use http_body_util::BodyExt;
        let references = [
            ImageReference::new(b"\x89PNG\r\n\x1a\nfirst".to_vec(), "image/png").unwrap(),
            ImageReference::new(b"\xff\xd8\xffsecond".to_vec(), "image/jpeg").unwrap(),
        ];
        for model in [
            "gpt-image-2",
            "gpt-image-1",
            "gpt-image-1.5",
            "gpt-image-1-mini",
            "compatible-model",
        ] {
            for count in [1, 2] {
                let config = ImageGenerationConfig {
                    provider: "openai".into(),
                    model: model.into(),
                    api_key: "secret".into(),
                    base_url: "https://example.com/v1".into(),
                };
                let form =
                    image_edit_form(&config, "combine", 1024, 1024, &references[..count], None)
                        .unwrap();
                let mut request = reqwest::Client::new()
                    .post("https://example.com/v1/images/edits")
                    .multipart(form)
                    .build()
                    .unwrap();
                let bytes = request
                    .body_mut()
                    .take()
                    .unwrap()
                    .collect()
                    .await
                    .unwrap()
                    .to_bytes();
                let body = String::from_utf8_lossy(&bytes);
                let field = if count == 1 {
                    "name=\"image\""
                } else {
                    "name=\"image[]\""
                };
                assert_eq!(body.matches(field).count(), count, "{model}");
                assert!(
                    body.contains("Content-Type: image/png")
                        || body.contains("content-type: image/png")
                );
                if count == 2 {
                    assert!(body.find("first").unwrap() < body.find("second").unwrap());
                }
                assert_eq!(
                    body.contains("input_fidelity"),
                    matches!(model, "gpt-image-1" | "gpt-image-1.5")
                );
            }
        }
    }

    #[test]
    fn gpt_image_2_openai_forces_json_envelope() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "gpt-image-2".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.openai.com/v1".to_string(),
        };
        let (_, body) =
            request_parts_with_background(&config, "portrait", 1000, 512, &[], None).unwrap();
        assert_eq!(body["model"], "gpt-image-2");
        assert_eq!(body["stream"], false);
        assert_eq!(body["background"], "opaque");
        assert_eq!(body["n"], 1);
        // 1000x512 snaps to 16px and is below gpt-image-2's pixel floor.
        assert_eq!(body["size"], "1024x1024");
    }

    #[test]
    fn gpt_image_2_snaps_supported_custom_size() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "openai/gpt-image-2-2026-04-21".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.openai.com/v1".to_string(),
        };
        let (_, body) =
            request_parts_with_background(&config, "portrait", 1000, 1000, &[], None).unwrap();
        assert_eq!(body["size"], "1008x1008");
        assert_eq!(body["stream"], false);
    }

    #[test]
    fn parses_base64_and_url_responses() {
        let base64 =
            parse_image_response(&json!({ "data": [{ "b64_json": "AA==" }] }), 1024, 1024).unwrap();
        assert_eq!(base64.source, "data:image/png;base64,AA==");
        let url = parse_image_response(
            &json!({ "data": [{ "url": "https://example.com/image.png", "size": "768x1024" }] }),
            1024,
            1024,
        )
        .unwrap();
        assert_eq!((url.width, url.height), (768, 1024));
        let jpeg = parse_image_response(
            &json!({
                "data": [{ "b64_json": "AA==" }],
                "output_format": "jpeg",
                "size": "1536x1024"
            }),
            1024,
            1024,
        )
        .unwrap();
        assert_eq!(jpeg.media_type, "image/jpeg");
        assert_eq!((jpeg.width, jpeg.height), (1536, 1024));
        assert_eq!(jpeg.source, "data:image/jpeg;base64,AA==");
    }

    #[test]
    fn parses_gpt_image_completed_sse_and_top_level_payloads() {
        let sse = concat!(
            "event: image_generation.partial_image\n",
            "data: {\"type\":\"image_generation.partial_image\",\"b64_json\":\"partial\"}\n",
            "\n",
            "event: image_generation.completed\n",
            "data: {\"type\":\"image_generation.completed\",\"b64_json\":\"AA==\",\"output_format\":\"png\",\"size\":\"1024x1536\"}\n",
            "\n",
        );
        let value = decode_provider_body(sse.as_bytes(), Some("text/event-stream")).unwrap();
        let parsed = parse_image_response(&value, 1024, 1024).unwrap();
        assert_eq!(parsed.source, "data:image/png;base64,AA==");
        assert_eq!((parsed.width, parsed.height), (1024, 1536));

        let top_level = parse_image_response(
            &json!({ "b64_json": "AA==", "output_format": "webp" }),
            512,
            512,
        )
        .unwrap();
        assert_eq!(top_level.source, "data:image/webp;base64,AA==");

        let responses = parse_image_response(
            &json!({
                "output": [{
                    "type": "image_generation_call",
                    "status": "completed",
                    "result": "AA=="
                }]
            }),
            1024,
            1024,
        )
        .unwrap();
        assert_eq!(responses.source, "data:image/png;base64,AA==");
    }

    #[test]
    fn decodes_gzip_wrapped_image_json() {
        use flate2::write::GzEncoder;
        use flate2::Compression;
        use std::io::Write;

        let json = serde_json::to_vec(&json!({ "data": [{ "b64_json": "AA==" }] })).unwrap();
        let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(&json).unwrap();
        let gz = encoder.finish().unwrap();
        let body = decompress_provider_body(&gz, Some("gzip")).unwrap();
        let value = decode_provider_body(&body, Some("application/json")).unwrap();
        let parsed = parse_image_response(&value, 1024, 1024).unwrap();
        assert_eq!(parsed.source, "data:image/png;base64,AA==");
    }

    #[test]
    fn classifies_provider_http_failures() {
        assert_eq!(
            image_generation_failure_code(&ImageGenerationError::Provider(
                "OpenRouter image API returned HTTP 402: {\"error\":\"Insufficient credits\"}"
                    .into()
            )),
            "image_provider_credits"
        );
        assert_eq!(
            image_generation_failure_code(&ImageGenerationError::Provider(
                "OpenRouter image API returned HTTP 401: unauthorized".into()
            )),
            "image_provider_unauthorized"
        );
        assert_eq!(
            image_generation_failure_code(&ImageGenerationError::Provider(
                "OpenRouter image API returned HTTP 429: rate limit".into()
            )),
            "image_provider_rate_limited"
        );
        assert_eq!(
            image_generation_failure_code(&ImageGenerationError::Provider(
                "OpenRouter image API returned HTTP 400: bad input_references".into()
            )),
            "image_provider_rejected"
        );
        assert_eq!(
            image_generation_failure_code(&ImageGenerationError::NotConfigured(
                "image provider is not configured".into()
            )),
            "image_provider_unconfigured"
        );
    }

    #[test]
    fn decode_error_includes_body_preview() {
        let error =
            decode_provider_body(b"event: nope\nnot-json", Some("text/event-stream")).unwrap_err();
        let message = error.to_string();
        assert!(
            message.contains("error decoding response body"),
            "{message}"
        );
        assert!(message.contains("event:"), "{message}");
    }

    #[test]
    fn rejects_mismatched_image_payload() {
        assert!(validate_magic(b"not a png", "image/png").is_err());
    }

    #[test]
    fn config_from_dynamic_rejects_unknown_provider_and_missing_keys() {
        let mut config = DynamicConfig::default();
        config.ai_image_provider = "unknown".to_string();
        assert!(matches!(
            config_from_dynamic(&config),
            Err(ImageGenerationError::UnsupportedProvider(provider)) if provider == "unknown"
        ));

        config.ai_image_provider = "openrouter".to_string();
        assert!(matches!(
            config_from_dynamic(&config),
            Err(ImageGenerationError::NotConfigured(_))
        ));

        config.openai_api_key = Some("sk-test".to_string());
        let resolved = config_from_dynamic(&config).unwrap();
        assert_eq!(resolved.provider, "openrouter");
        assert_eq!(resolved.base_url, "https://openrouter.ai/api/v1");

        config.ai_image_provider = "gemini".to_string();
        config.ai_image_model = "gemini-3.1-flash-image".to_string();
        config.gemini_api_key = Some("AIza-test".to_string());
        let gemini = config_from_dynamic(&config).unwrap();
        assert_eq!(gemini.provider, "gemini");
        assert_eq!(gemini.model, "gemini-3.1-flash-image");
        assert_eq!(gemini.base_url, "https://generativelanguage.googleapis.com");

        config.ai_image_provider = "openrouter".to_string();
        config.ai_image_source = "work-gemini".to_string();
        config.ai_vendor_sources = vec![crate::config::AiVendorSource {
            slug: "work-gemini".to_string(),
            kind: "Gemini".to_string(),
            display_name: "Gemini Work".to_string(),
            enabled: true,
            preset: "gemini".to_string(),
            api_key: Some("AIza-source".to_string()),
            ..crate::config::AiVendorSource::default()
        }];
        let from_source = config_from_dynamic(&config).unwrap();
        assert_eq!(from_source.provider, "gemini");
        assert_eq!(from_source.api_key, "AIza-source");
    }
}
