//! Configured image providers: OpenAI-compatible, OpenRouter, Volcengine Ark, Gemini.
//!
//! Resolution is chosen by the caller. Generated bytes are persisted into the
//! local image cache so Agent / Tapp surfaces get a stable `/api/...` URL
//! instead of a short-lived provider link or an inline data URL.

use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use serde_json::{json, Map, Value};
use std::time::Duration;

use crate::{
    config::DynamicConfig,
    services::{http_client::get_long_running_client, image_cache::ImageCacheService},
};

const MAX_PROMPT_CHARS: usize = 32_680;
const MAX_IMAGE_BYTES: usize = 10 * 1024 * 1024;

#[derive(Clone, Debug)]
pub struct ImageGenerationConfig {
    pub provider: String,
    pub model: String,
    pub api_key: String,
    pub base_url: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedImage {
    pub source: String,
    pub media_type: String,
    pub width: u32,
    pub height: u32,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImageReference {
    pub bytes: Vec<u8>,
    pub media_type: String,
}

impl ImageReference {
    pub fn new(bytes: Vec<u8>, media_type: impl Into<String>) -> Result<Self, ImageGenerationError> {
        let media_type = media_type.into();
        validate_media_type(&media_type)?;
        validate_magic(&bytes, &media_type)?;
        Ok(Self { bytes, media_type })
    }

    fn data_url(&self) -> String {
        format!(
            "data:{};base64,{}",
            self.media_type,
            BASE64.encode(&self.bytes)
        )
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ImageGenerationError {
    NotConfigured(String),
    UnsupportedProvider(String),
    Provider(String),
    InvalidResponse(String),
}

impl std::fmt::Display for ImageGenerationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotConfigured(message)
            | Self::Provider(message)
            | Self::InvalidResponse(message) => formatter.write_str(message),
            Self::UnsupportedProvider(provider) => {
                write!(formatter, "unsupported image provider: {provider}")
            }
        }
    }
}

impl std::error::Error for ImageGenerationError {}

pub fn config_from_dynamic(
    dynamic: &DynamicConfig,
) -> Result<ImageGenerationConfig, ImageGenerationError> {
    let source = dynamic.find_vendor_source(&dynamic.ai_image_source);
    let provider = source
        .as_ref()
        .map(|item| image_protocol(&item.kind))
        .filter(|item| !item.is_empty())
        .unwrap_or_else(|| image_protocol(&dynamic.ai_image_provider));
    if provider.is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image provider is not configured".to_string(),
        ));
    }
    let (api_key, base_url) = if let Some(source) = source.as_ref() {
        match source.kind.trim().to_ascii_lowercase().as_str() {
            "openai" | "openai_compatible" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_openai_api_key()),
                if source.base_url.trim().is_empty() {
                    dynamic.shared_openai_base_url()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "openrouter" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_openrouter_api_key()),
                if source.base_url.trim().is_empty() {
                    "https://openrouter.ai/api/v1".to_string()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "volcengine" | "ark" | "seedream" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_volcengine_api_key()),
                if source.base_url.trim().is_empty() {
                    dynamic.shared_volcengine_base_url()
                } else {
                    source.base_url.trim().to_string()
                },
            ),
            "gemini" => (
                DynamicConfig::nonempty_opt(source.api_key.as_ref())
                    .or_else(|| dynamic.shared_gemini_api_key()),
                gemini_image_base_url(dynamic, Some(source)),
            ),
            other => return Err(ImageGenerationError::UnsupportedProvider(other.to_string())),
        }
    } else {
        match provider.as_str() {
            "openai" => (
                dynamic.shared_openai_api_key(),
                dynamic.shared_openai_base_url(),
            ),
            "openrouter" => (
                dynamic.shared_openrouter_api_key(),
                "https://openrouter.ai/api/v1".to_string(),
            ),
            "volcengine" | "ark" | "seedream" => (
                dynamic.shared_volcengine_api_key(),
                dynamic.shared_volcengine_base_url(),
            ),
            "gemini" => (
                dynamic.shared_gemini_api_key(),
                gemini_image_base_url(dynamic, None),
            ),
            other => {
                return Err(ImageGenerationError::UnsupportedProvider(other.to_string()))
            }
        }
    };
    let api_key = api_key.ok_or_else(|| {
        ImageGenerationError::NotConfigured(format!(
            "{} image API key is not configured",
            provider_label(&provider)
        ))
    })?;
    if dynamic.ai_image_model.trim().is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image model is not configured".to_string(),
        ));
    }
    if base_url.is_empty() {
        return Err(ImageGenerationError::NotConfigured(
            "image provider base URL is not configured".to_string(),
        ));
    }
    Ok(ImageGenerationConfig {
        provider,
        model: dynamic.ai_image_model.trim().to_string(),
        api_key: api_key.to_string(),
        base_url: base_url.trim_end_matches('/').to_string(),
    })
}

pub async fn generate_image(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    reference: Option<&ImageReference>,
) -> Result<GeneratedImage, ImageGenerationError> {
    let prompt = prompt.trim();
    if prompt.is_empty() || prompt.chars().count() > MAX_PROMPT_CHARS {
        return Err(ImageGenerationError::Provider(format!(
            "image prompt must contain 1 to {MAX_PROMPT_CHARS} characters"
        )));
    }
    let width = width.clamp(256, 2048);
    let height = height.clamp(256, 2048);
    if config.provider == "gemini" {
        return crate::services::gemini_media::generate_image(
            config, prompt, width, height, reference,
        )
        .await;
    }
    let client = get_long_running_client().await;
    let response = if config.provider == "openai" {
        if let Some(reference) = reference {
            let options = request_options(config);
            let endpoint = format!("{}/images/edits", config.base_url);
            let part = reqwest::multipart::Part::bytes(reference.bytes.clone())
                .file_name(reference_file_name(&reference.media_type))
                .mime_str(&reference.media_type)
                .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
            let mut form = reqwest::multipart::Form::new()
                .text("model", strip_openai_prefix(&config.model).to_string())
                .text("prompt", prompt.to_string())
                .text("size", format!("{width}x{height}"))
                .text("input_fidelity", "high");
            if options.include_n {
                form = form.text("n", "1");
            }
            if let Some(background) = options.background {
                form = form.text("background", background);
            }
            if let Some(output_format) = options.output_format {
                form = form.text("output_format", output_format);
            }
            let form = form.part("image", part);
            client
                .post(endpoint)
                .bearer_auth(&config.api_key)
                .multipart(form)
                .send()
                .await
        } else {
            let (endpoint, body) = request_parts(config, prompt, width, height, None)?;
            client
                .post(endpoint)
                .bearer_auth(&config.api_key)
                .json(&body)
                .send()
                .await
        }
    } else {
        let reference_data_url = reference.map(ImageReference::data_url);
        let (endpoint, body) = request_parts(
            config,
            prompt,
            width,
            height,
            reference_data_url.as_deref(),
        )?;
        client
            .post(endpoint)
            .bearer_auth(&config.api_key)
            .json(&body)
            .send()
            .await
    }
    .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        let body: String = body.chars().take(600).collect();
        return Err(ImageGenerationError::Provider(format!(
            "{} image API returned HTTP {status}: {body}",
            provider_label(&config.provider)
        )));
    }
    let value: Value = response
        .json()
        .await
        .map_err(|error| ImageGenerationError::InvalidResponse(error.to_string()))?;
    parse_image_response(&value, width, height)
}

/// Persist a provider result into the local image cache and return a serveable URL.
pub async fn persist_generated(
    generated: &GeneratedImage,
) -> Result<String, ImageGenerationError> {
    let (bytes, media_type) = load_generated_bytes(generated).await?;
    ImageCacheService::new()
        .store_bytes(&bytes, &media_type)
        .await
        .map_err(ImageGenerationError::Provider)
}

async fn load_generated_bytes(
    generated: &GeneratedImage,
) -> Result<(Vec<u8>, String), ImageGenerationError> {
    if let Some(data) = generated.source.strip_prefix("data:") {
        let (metadata, encoded) = data.split_once(',').ok_or_else(|| {
            ImageGenerationError::InvalidResponse("invalid image data URL".to_string())
        })?;
        if !metadata.ends_with(";base64") {
            return Err(ImageGenerationError::InvalidResponse(
                "image data URL is not base64 encoded".to_string(),
            ));
        }
        let media_type = metadata.trim_end_matches(";base64");
        validate_media_type(media_type)?;
        let bytes = BASE64.decode(encoded).map_err(|_| {
            ImageGenerationError::InvalidResponse("invalid image base64".to_string())
        })?;
        if bytes.len() > MAX_IMAGE_BYTES {
            return Err(ImageGenerationError::InvalidResponse(
                "generated image exceeds storage limit".to_string(),
            ));
        }
        validate_magic(&bytes, media_type)?;
        return Ok((bytes, media_type.to_string()));
    }

    let (url, client) = crate::services::outbound_security::build_public_http_client(
        &generated.source,
        Duration::from_secs(120),
        Some("Myriad-ImageGeneration/1.0"),
    )
    .await
    .map_err(ImageGenerationError::InvalidResponse)?;
    let response = client
        .get(url)
        .send()
        .await
        .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
    if !response.status().is_success() {
        return Err(ImageGenerationError::Provider(format!(
            "generated image download returned HTTP {}",
            response.status()
        )));
    }
    if response.content_length().unwrap_or(0) > MAX_IMAGE_BYTES as u64 {
        return Err(ImageGenerationError::InvalidResponse(
            "generated image exceeds storage limit".to_string(),
        ));
    }
    let media_type = response
        .headers()
        .get(reqwest::header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.split(';').next())
        .unwrap_or(&generated.media_type)
        .to_string();
    validate_media_type(&media_type)?;
    let bytes = response
        .bytes()
        .await
        .map_err(|error| ImageGenerationError::Provider(error.to_string()))?;
    if bytes.len() > MAX_IMAGE_BYTES {
        return Err(ImageGenerationError::InvalidResponse(
            "generated image exceeds storage limit".to_string(),
        ));
    }
    validate_magic(&bytes, &media_type)?;
    Ok((bytes.to_vec(), media_type))
}

fn request_parts(
    config: &ImageGenerationConfig,
    prompt: &str,
    width: u32,
    height: u32,
    reference_data_url: Option<&str>,
) -> Result<(String, Value), ImageGenerationError> {
    let size = format!("{width}x{height}");
    let options = request_options(config);
    match config.provider.as_str() {
        "openai" => {
            let mut body = json!({
                "model": strip_openai_prefix(&config.model),
                "prompt": prompt,
                "size": size
            });
            if options.include_n {
                body["n"] = json!(1);
            }
            apply_background_options(&mut body, options);
            Ok((format!("{}/images/generations", config.base_url), body))
        }
        "openrouter" => {
            let mut body = json!({
                "model": config.model,
                "prompt": prompt,
                "aspect_ratio": aspect_ratio(width, height)
            });
            if options.include_n {
                body["n"] = json!(1);
            }
            apply_background_options(&mut body, options);
            if let Some(reference) = reference_data_url {
                body["input_references"] = json!([{
                    "type": "image_url",
                    "image_url": { "url": reference }
                }]);
            }
            Ok((format!("{}/images", config.base_url), body))
        }
        "volcengine" | "ark" | "seedream" => {
            let mut body = Map::new();
            body.insert("model".to_string(), json!(config.model));
            body.insert("prompt".to_string(), json!(prompt));
            body.insert("size".to_string(), json!(size));
            body.insert("response_format".to_string(), json!("url"));
            body.insert("sequential_image_generation".to_string(), json!("disabled"));
            body.insert("watermark".to_string(), json!(false));
            body.insert("stream".to_string(), json!(false));
            if let Some(reference) = reference_data_url {
                body.insert("image".to_string(), json!([reference]));
            }
            Ok((
                format!("{}/images/generations", config.base_url),
                Value::Object(body),
            ))
        }
        other => Err(ImageGenerationError::UnsupportedProvider(other.to_string())),
    }
}

#[derive(Clone, Copy)]
struct ImageRequestOptions {
    background: Option<&'static str>,
    output_format: Option<&'static str>,
    include_n: bool,
}

fn request_options(config: &ImageGenerationConfig) -> ImageRequestOptions {
    if config.provider == "openrouter" {
        let native_transparency = is_gpt_image_1(&config.model);
        return ImageRequestOptions {
            background: native_transparency.then_some("transparent"),
            output_format: None,
            include_n: false,
        };
    }
    if is_gpt_image_2(&config.model) {
        return ImageRequestOptions {
            background: Some("opaque"),
            output_format: None,
            include_n: true,
        };
    }
    if is_gpt_image_1(&config.model) {
        return ImageRequestOptions {
            background: Some("transparent"),
            output_format: Some("png"),
            include_n: true,
        };
    }
    ImageRequestOptions {
        background: None,
        output_format: None,
        include_n: true,
    }
}

fn is_gpt_image_2(model: &str) -> bool {
    strip_openai_prefix(model).eq_ignore_ascii_case("gpt-image-2")
}

fn is_gpt_image_1(model: &str) -> bool {
    matches!(
        strip_openai_prefix(model).to_ascii_lowercase().as_str(),
        "gpt-image-1" | "gpt-image-1-mini"
    )
}

fn apply_background_options(body: &mut Value, options: ImageRequestOptions) {
    if let Some(background) = options.background {
        body["background"] = json!(background);
    }
    if let Some(output_format) = options.output_format {
        body["output_format"] = json!(output_format);
    }
}

fn aspect_ratio(width: u32, height: u32) -> &'static str {
    if width == height {
        "1:1"
    } else if width.saturating_mul(2) == height.saturating_mul(3) {
        "3:2"
    } else if width.saturating_mul(3) == height.saturating_mul(2) {
        "2:3"
    } else if width > height {
        "16:9"
    } else {
        "9:16"
    }
}

fn reference_file_name(media_type: &str) -> &'static str {
    match media_type {
        "image/jpeg" => "character-reference.jpg",
        "image/webp" => "character-reference.webp",
        _ => "character-reference.png",
    }
}

fn parse_image_response(
    value: &Value,
    width: u32,
    height: u32,
) -> Result<GeneratedImage, ImageGenerationError> {
    let item = value
        .get("data")
        .and_then(Value::as_array)
        .and_then(|items| items.first())
        .ok_or_else(|| {
            ImageGenerationError::InvalidResponse("response contained no image data".to_string())
        })?;
    let media_type = item
        .get("media_type")
        .and_then(Value::as_str)
        .unwrap_or("image/png")
        .to_string();
    let source = item
        .get("b64_json")
        .and_then(Value::as_str)
        .map(|encoded| format!("data:{media_type};base64,{encoded}"))
        .or_else(|| item.get("url").and_then(Value::as_str).map(str::to_string))
        .ok_or_else(|| {
            ImageGenerationError::InvalidResponse(
                "response image has neither b64_json nor url".to_string(),
            )
        })?;
    let (width, height) = item
        .get("size")
        .and_then(Value::as_str)
        .and_then(|size| size.split_once('x'))
        .and_then(|(width, height)| Some((width.parse().ok()?, height.parse().ok()?)))
        .unwrap_or((width, height));
    Ok(GeneratedImage {
        source,
        media_type,
        width,
        height,
    })
}

fn validate_media_type(media_type: &str) -> Result<(), ImageGenerationError> {
    if matches!(media_type, "image/png" | "image/jpeg" | "image/webp") {
        Ok(())
    } else {
        Err(ImageGenerationError::InvalidResponse(format!(
            "unsupported generated image media type: {media_type}"
        )))
    }
}

fn validate_magic(bytes: &[u8], media_type: &str) -> Result<(), ImageGenerationError> {
    let valid = match media_type {
        "image/png" => bytes.starts_with(b"\x89PNG\r\n\x1a\n"),
        "image/jpeg" => bytes.starts_with(&[0xff, 0xd8, 0xff]),
        "image/webp" => bytes.starts_with(b"RIFF") && bytes.get(8..12) == Some(b"WEBP"),
        _ => false,
    };
    valid.then_some(()).ok_or_else(|| {
        ImageGenerationError::InvalidResponse(
            "generated payload does not match its image media type".to_string(),
        )
    })
}

fn clean_key(value: Option<&str>) -> Option<&str> {
    value.map(str::trim).filter(|value| !value.is_empty())
}

fn strip_openai_prefix(model: &str) -> &str {
    model.strip_prefix("openai/").unwrap_or(model)
}

fn image_protocol(kind: &str) -> String {
    match kind.trim().to_ascii_lowercase().as_str() {
        "gemini" => "gemini".to_string(),
        "volcengine" | "ark" | "seedream" => "volcengine".to_string(),
        "openrouter" => "openrouter".to_string(),
        "openai" | "openai_compatible" => "openai".to_string(),
        other => other.to_string(),
    }
}

fn gemini_image_base_url(
    dynamic: &DynamicConfig,
    source: Option<&crate::config::AiVendorSource>,
) -> String {
    if let Some(source) = source {
        let custom = source.base_url.trim();
        if !custom.is_empty() {
            return custom.trim_end_matches('/').to_string();
        }
    }
    dynamic
        .gemini_base_url
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("https://generativelanguage.googleapis.com")
        .trim_end_matches('/')
        .to_string()
}

fn provider_label(provider: &str) -> &str {
    match provider {
        "openai" => "OpenAI",
        "openrouter" => "OpenRouter",
        "volcengine" | "ark" | "seedream" => "Volcengine Ark",
        "gemini" => "Gemini",
        _ => provider,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DynamicConfig;

    #[test]
    fn builds_each_supported_provider_request() {
        for (provider, expected_suffix) in [
            ("openai", "/images/generations"),
            ("openrouter", "/images"),
            ("volcengine", "/images/generations"),
        ] {
            let config = ImageGenerationConfig {
                provider: provider.to_string(),
                model: "model".to_string(),
                api_key: "secret".to_string(),
                base_url: "https://example.com/v1".to_string(),
            };
            let (endpoint, body) = request_parts(&config, "portrait", 1024, 1024, None).unwrap();
            assert!(endpoint.ends_with(expected_suffix));
            assert_eq!(body["model"], "model");
            assert_eq!(body["prompt"], "portrait");
        }
    }

    #[test]
    fn compatible_image_models_omit_openai_only_fields() {
        let config = ImageGenerationConfig {
            provider: "openai".to_string(),
            model: "Kwai-Kolors/Kolors".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://api.siliconflow.cn/v1".to_string(),
        };
        let (_, body) = request_parts(&config, "portrait", 1024, 1024, None).unwrap();
        assert_eq!(body["model"], "Kwai-Kolors/Kolors");
        assert_eq!(body["size"], "1024x1024");
        assert_eq!(body["n"], 1);
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
    }

    #[test]
    fn gpt_image_2_uses_supported_background_contract() {
        let config = ImageGenerationConfig {
            provider: "openrouter".to_string(),
            model: "openai/gpt-image-2".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://openrouter.ai/api/v1".to_string(),
        };
        let (_, body) = request_parts(&config, "portrait", 1024, 1024, None).unwrap();
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
        assert!(body.get("n").is_none());
        assert_eq!(body["aspect_ratio"], "1:1");
    }

    #[test]
    fn openrouter_only_sends_optional_parameters_known_to_be_supported() {
        let generic = ImageGenerationConfig {
            provider: "openrouter".to_string(),
            model: "qwen/qwen-image-3".to_string(),
            api_key: "secret".to_string(),
            base_url: "https://openrouter.ai/api/v1".to_string(),
        };
        let (_, body) = request_parts(&generic, "portrait", 1536, 1024, None).unwrap();
        assert_eq!(body["aspect_ratio"], "3:2");
        assert!(body.get("background").is_none());
        assert!(body.get("output_format").is_none());
        assert!(body.get("n").is_none());

        let transparent = ImageGenerationConfig {
            model: "openai/gpt-image-1".to_string(),
            ..generic
        };
        let (_, body) = request_parts(&transparent, "portrait", 1024, 1024, None).unwrap();
        assert_eq!(body["background"], "transparent");
        assert!(body.get("output_format").is_none());
    }

    #[test]
    fn reference_requests_use_provider_native_contracts() {
        let reference = "data:image/png;base64,AA==";
        for (provider, key) in [("openrouter", "input_references"), ("volcengine", "image")] {
            let config = ImageGenerationConfig {
                provider: provider.to_string(),
                model: "model".to_string(),
                api_key: "secret".to_string(),
                base_url: "https://example.com/v1".to_string(),
            };
            let (_, body) =
                request_parts(&config, "turn around", 1024, 1024, Some(reference)).unwrap();
            assert!(body.get(key).is_some());
        }
    }

    #[test]
    fn image_reference_rejects_spoofed_media_type() {
        assert!(ImageReference::new(b"not png".to_vec(), "image/png").is_err());
    }

    #[test]
    fn parses_base64_and_url_responses() {
        let base64 =
            parse_image_response(&json!({ "data": [{ "b64_json": "AA==" }] }), 1024, 1024).unwrap();
        assert_eq!(base64.source, "data:image/png;base64,AA==");
        let url = parse_image_response(
            &json!({ "data": [{ "url": "https://example.com/image.png", "size": "768x1024" }] }),
            1024,
            1024,
        )
        .unwrap();
        assert_eq!((url.width, url.height), (768, 1024));
    }

    #[test]
    fn rejects_mismatched_image_payload() {
        assert!(validate_magic(b"not a png", "image/png").is_err());
    }

    #[test]
    fn config_from_dynamic_rejects_unknown_provider_and_missing_keys() {
        let mut config = DynamicConfig::default();
        config.ai_image_provider = "unknown".to_string();
        assert!(matches!(
            config_from_dynamic(&config),
            Err(ImageGenerationError::UnsupportedProvider(provider)) if provider == "unknown"
        ));

        config.ai_image_provider = "openrouter".to_string();
        assert!(matches!(
            config_from_dynamic(&config),
            Err(ImageGenerationError::NotConfigured(_))
        ));

        config.openai_api_key = Some("sk-test".to_string());
        let resolved = config_from_dynamic(&config).unwrap();
        assert_eq!(resolved.provider, "openrouter");
        assert_eq!(resolved.base_url, "https://openrouter.ai/api/v1");

        config.ai_image_provider = "gemini".to_string();
        config.ai_image_model = "gemini-3.1-flash-image".to_string();
        config.gemini_api_key = Some("AIza-test".to_string());
        let gemini = config_from_dynamic(&config).unwrap();
        assert_eq!(gemini.provider, "gemini");
        assert_eq!(gemini.model, "gemini-3.1-flash-image");
        assert_eq!(
            gemini.base_url,
            "https://generativelanguage.googleapis.com"
        );

        config.ai_image_provider = "openrouter".to_string();
        config.ai_image_source = "work-gemini".to_string();
        config.ai_vendor_sources = vec![crate::config::AiVendorSource {
            slug: "work-gemini".to_string(),
            kind: "Gemini".to_string(),
            display_name: "Gemini Work".to_string(),
            enabled: true,
            preset: "gemini".to_string(),
            api_key: Some("AIza-source".to_string()),
            ..crate::config::AiVendorSource::default()
        }];
        let from_source = config_from_dynamic(&config).unwrap();
        assert_eq!(from_source.provider, "gemini");
        assert_eq!(from_source.api_key, "AIza-source");
    }
}
