import { fileURLToPath } from 'node:url'
import { expect, test } from '@playwright/test'

test('optional pose editor leaves playback alone until expanded and preserves collapsed drafts', async ({ page }) => {
  const fixture = `/@fs${fileURLToPath(new URL('./fixture/poseCorrectionEditor.tsx', import.meta.url))}`
  await page.route('**/pose-editor-probe', route => route.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }))
  await page.goto('/pose-editor-probe')
  await page.evaluate(async fixture => {
    const { mountPoseEditor } = await import(fixture)
    window.poseEditorProbe = await mountPoseEditor()
  }, fixture)
  const group = page.locator('#merope-pose-corrections')
  const toggle = group.locator('.setting-group-header-toggle')
  const add = group.locator('.merope-pose__step').nth(1).getByRole('button', { name: 'Left eye', exact: true })
  const remove = group.getByRole('button', { name: 'Delete this spot', exact: true })
  const save = group.getByRole('button', { name: 'Save', exact: true })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(add).toHaveCount(0)
  expect(await page.evaluate(() => window.poseEditorProbe.calls)).toEqual([])
  await toggle.click()
  await expect(add).toBeVisible()
  await add.click()
  await expect(remove).toBeVisible()
  await expect(save).toBeEnabled()
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.calls.at(-1)?.length)).toBe(1)
  await toggle.click()
  await expect(add).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.calls.at(-1))).toBeNull()
  expect(await page.evaluate(() => window.poseEditorProbe.saves)).toEqual([])
  await toggle.click()
  await expect(remove).toBeVisible()
  await expect(save).toBeEnabled()
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.calls.at(-1)?.length)).toBe(1)
  await save.click()
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.saves.length)).toBe(1)
  await page.evaluate(() => window.poseEditorProbe.render('second-outfit'))
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.calls.at(-1))).toBeNull()
  await toggle.click()
  await expect(add).toBeVisible()
  await expect(remove).toHaveCount(0)
  await expect(save).toBeDisabled()
  await page.evaluate(() => window.poseEditorProbe.unmount())
  await expect.poll(() => page.evaluate(() => window.poseEditorProbe.calls.at(-1))).toBeNull()
})
