import type { Page } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { expect, test } from '@playwright/test'

const fixture = `/@fs${fileURLToPath(new URL('./fixture/tappWindows.tsx', import.meta.url))}`

async function mount(page: Page, mode: 'single' | 'multi') {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.route('**/tapp-window-probe', (route) => route.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }))
  await page.route('**/api/**', (route) => {
    const request = route.request()
    if (request.url().endsWith('/runtime-grants')) {
      const { instanceId, kind } = request.postDataJSON()
      const tappId = request.url().split('/').at(-2)
      return route.fulfill({ json: {
        version: 2, token: `fixture-${instanceId}`, runtimeId: instanceId,
        tappId, ownerId: 1, subjectId: 0, instanceId, kind, permissions: [],
        expiresAt: new Date(Date.now() + 3600_000).toISOString(),
      } })
    }
    return route.fulfill({ json: request.url().includes('csrf-token') ? { csrf_token: null } : {} })
  })
  await page.goto('/tapp-window-probe')
  await page.evaluate(async ({ fixture, mode }) => { (await import(fixture)).mount(mode) }, { fixture, mode })
  await expect(page.frameLocator('iframe').getByRole('button', { name: 'Count 0' })).toBeVisible()
}

test('single app keeps fullscreen on its existing button without a title gesture or chat entry', async ({ page }) => {
  await mount(page, 'single')
  const original = await page.locator('iframe').elementHandle()
  const frame = page.frameLocator('iframe')
  const boot = await frame.locator('body').getAttribute('data-boot')
  await frame.getByRole('button', { name: 'Count 0' }).click()
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await expect(page.locator('[data-tapp-titlebar] button')).toHaveCount(3)
  const title = page.locator('[data-tapp-titlebar]:visible').getByText('Window One', { exact: true })
  await title.dblclick()
  await expect(page.getByTitle('Exit fullscreen')).toHaveCount(0)
  await page.getByTitle('Fullscreen', { exact: true }).click()
  await expect(page.getByTitle('Exit fullscreen')).toBeVisible()
  expect(await page.locator('iframe').evaluate((node, original) => node === original, original)).toBe(true)
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await page.getByRole('heading', { name: 'Window One', exact: true }).dblclick()
  await expect(page.getByTitle('Exit fullscreen')).toBeVisible()
  await page.getByTitle('Exit fullscreen').click()
  await expect(page.getByTitle('Fullscreen', { exact: true })).toBeVisible()
  expect(await frame.locator('body').getAttribute('data-boot')).toBe(boot)
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
})

test('desktop title enters smart split, repeats against current bounds and preserves app state', async ({ page }) => {
  await mount(page, 'multi')
  const app = page.locator('[data-tapp-window]').first()
  const original = await app.locator('iframe').elementHandle()
  const frame = app.frameLocator('iframe')
  await frame.getByRole('button', { name: 'Count 0' }).click()
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await page.evaluate(async fixture => { await (await import(fixture)).openWindow('fixture.two') }, fixture)
  const other = page.locator('[data-tapp-window]').nth(1)
  await expect(other.frameLocator('iframe').getByRole('button', { name: 'Count 0' })).toBeVisible()
  const title = other.locator('[data-tapp-titlebar]').getByText('Window Two', { exact: true })
  await title.dblclick()
  await expect(app.locator('.tapp-window-resize-handle')).toHaveCount(8)
  let left = await app.boundingBox()
  let right = await other.boundingBox()
  expect(left!.x).toBe(16)
  expect(left!.y).toBe(80)
  expect(left!.width).toBe(698)
  expect(right!.x).toBe(left!.x + left!.width + 12)
  expect(right!.y).toBe(left!.y)
  const split = [left, right]
  await title.dblclick()
  expect([await app.boundingBox(), await other.boundingBox()]).toEqual(split)
  await page.setViewportSize({ width: 1280, height: 900 })
  await title.dblclick()
  await expect.poll(async () => (await app.boundingBox())!.width).toBe(618)
  const desktop = await page.locator('.tapp-multi-desktop').boundingBox()
  left = await app.boundingBox()
  right = await other.boundingBox()
  expect(right!.x + right!.width).toBe(1264)
  expect(left!.height).toBeCloseTo(desktop!.height - 96, 1)
  expect(await app.locator('iframe').evaluate((node, original) => node === original, original)).toBe(true)
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await app.getByRole('button', { name: 'Minimize' }).dispatchEvent('dblclick')
  expect([await app.boundingBox(), await other.boundingBox()]).toEqual([left, right])
})

test('smart split keeps a lone visible app in one half even when another app is minimized', async ({ page }, testInfo) => {
  await mount(page, 'multi')
  const app = page.locator('[data-tapp-window]').first()
  const title = app.locator('[data-tapp-titlebar]').getByText('Window One', { exact: true })
  const original = await app.locator('iframe').elementHandle()
  const frame = app.frameLocator('iframe')
  await frame.getByRole('button', { name: 'Count 0' }).click()
  await title.dblclick()
  let half = await app.boundingBox()
  expect(half!.x).toBe(16)
  expect(half!.y).toBe(80)
  expect(half!.width).toBe(698)
  const desktop = await page.locator('.tapp-multi-desktop').boundingBox()
  expect(half!.width * half!.height).toBeLessThan(desktop!.width * desktop!.height / 2)
  await title.dblclick()
  expect(await app.boundingBox()).toEqual(half)

  await page.evaluate(async fixture => { await (await import(fixture)).openWindow('fixture.two') }, fixture)
  const other = page.locator('[data-tapp-window]').nth(1)
  await expect(other.frameLocator('iframe').getByRole('button', { name: 'Count 0' })).toBeVisible()
  await other.getByRole('button', { name: 'Minimize' }).click()
  await expect(other).toBeHidden()
  await page.getByRole('button', { name: 'Smart split' }).click()
  expect(await app.boundingBox()).toEqual(half)

  await page.setViewportSize({ width: 900, height: 1500 })
  await title.dblclick()
  await expect.poll(async () => (await app.boundingBox())!.height).toBeLessThan(700)
  half = await app.boundingBox()
  expect(half!.width).toBe(868)
  const tallDesktop = await page.locator('.tapp-multi-desktop').boundingBox()
  expect(half!.height).toBeCloseTo((tallDesktop!.height - 96 - 12) / 2, 1)
  expect(await app.locator('iframe').evaluate((node, original) => node === original, original)).toBe(true)
  await expect(frame.getByRole('button', { name: 'Count 1' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('single-window-smart-split.png') })
})

test('smart split arranges visible windows below controls and above the dock, preserving minimized apps', async ({ page }, testInfo) => {
  await mount(page, 'multi')
  for (const id of ['fixture.two', 'fixture.three']) {
    await page.evaluate(async ({ fixture, id }) => { await (await import(fixture)).openWindow(id) }, { fixture, id })
    await expect(page.locator(`[data-window-id][data-tapp-id="${id}"] iframe`)).toHaveCount(1)
  }
  const apps = page.locator('[data-tapp-window]')
  await expect(apps).toHaveCount(3)
  const originals = await page.locator('iframe').elementHandles()
  const hidden = apps.nth(2)
  const hiddenGeometry = await hidden.evaluate((node) => ({ transform: (node as HTMLElement).style.transform, width: (node as HTMLElement).style.width, height: (node as HTMLElement).style.height }))
  await hidden.getByRole('button', { name: 'Minimize' }).click()
  await expect(hidden).toBeHidden()
  await page.getByRole('button', { name: 'Smart split' }).click()
  const left = await apps.nth(0).boundingBox()
  const right = await apps.nth(1).boundingBox()
  const desktop = await page.locator('.tapp-multi-desktop').boundingBox()
  expect(left!.y).toBe(80)
  expect(right!.y).toBe(80)
  expect(left!.x + left!.width).toBeLessThan(right!.x)
  expect(right!.x + right!.width).toBeLessThanOrEqual(desktop!.width - 16)
  expect(left!.y + left!.height).toBeLessThanOrEqual(desktop!.height - 15)
  expect(await hidden.evaluate((node) => ({ transform: (node as HTMLElement).style.transform, width: (node as HTMLElement).style.width, height: (node as HTMLElement).style.height }))).toEqual(hiddenGeometry)
  await expect(page.locator('iframe')).toHaveCount(3)
  for (const original of originals) expect(await original.evaluate((node) => node.isConnected)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('smart-split.png') })
})
