//! Expected table definitions (tables_phantasi).
use super::types::{ColumnDef, TableDef};

pub(crate) fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "phantasi_note_history".into(),
            columns: vec![
                ColumnDef {
                    name: "doc_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "revision".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "actor_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "snapshot".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "saved_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_sources".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "feed_type".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'rss'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "source_type".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'rss'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "category".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "icon".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "description".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "site_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "update_interval".into(),
                    data_type: "integer".into(),
                    default_value: Some("30".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "last_fetched_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_success_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_error".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "error_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "enabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("true".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "item_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "card_size".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "theme_color".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "sort_order".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "ai_style_tags".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "extra_config".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "rsshub_route".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "admin_only".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_items".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "source_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "guid".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "link".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "summary".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "author".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "image".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "audio_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "video_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "enclosures".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "categories".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "published_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "fetched_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "word_count".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reading_time".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "fulltext_fetched".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                // 预定义主题 key。NULL = 未分类，不进主题聚类。
                ColumnDef {
                    name: "topic".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                // 笔记原文（Markdown）。抓来的文章恒为 NULL；渲染后的 HTML
                // 仍然落在 content 上，全站只认那一列。
                ColumnDef {
                    name: "content_md".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content_revision".into(),
                    data_type: "bigint".into(),
                    default_value: Some("1".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_user_states".to_string(),
            columns: vec![
                ColumnDef {
                    name: "revision".into(),
                    data_type: "bigint".into(),
                    default_value: Some("1".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "item_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_read".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_starred".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "read_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "read_progress".into(),
                    data_type: "real".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "starred_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "notes".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_categories".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "icon".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "color".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "sort_order".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_annotations".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "item_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "annotation_type".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'term'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "term".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "explanation".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "position".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "context_hint".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_podcasts".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "item_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "language".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "dialogues".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "estimated_duration".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_comments".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "item_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "selected_text".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "comment".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "start_offset".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "end_offset".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "context_before".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "context_after".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "color".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_public".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "parent_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "content_revision".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "rsshub_instances".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "access_key".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "priority".into(),
                    data_type: "integer".into(),
                    default_value: Some("100".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "enabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("true".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "health_status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'unknown'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "last_health_check".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_response_time_ms".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "consecutive_failures".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "total_requests".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "success_requests".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_note_docs".to_string(),
            columns: vec![
                ColumnDef {
                    name: "last_edited_by".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "item_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "text".into(),
                    default_value: Some("''".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "content_md".into(),
                    data_type: "text".into(),
                    default_value: Some("''".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "topic".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "image".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'draft'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "scheduled_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "published_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "revision".into(),
                    data_type: "bigint".into(),
                    default_value: Some("1".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "last_error".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "phantasi_note_authors".to_string(),
            columns: vec![
                ColumnDef {
                    name: "doc_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "role".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'author'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "media_assets".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "kind".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mime".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "text".into(),
                    default_value: Some("''".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "size".into(),
                    data_type: "bigint".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef::new("public_id", "uuid").default_value("gen_random_uuid()"),
                ColumnDef::new("scope", "text").default_value("'legacy_unknown'"),
                ColumnDef::new("owner_user_id", "integer"),
                ColumnDef::new("created_by", "integer"),
                ColumnDef::new("storage_key", "text"),
                ColumnDef::new("state", "text"),
                ColumnDef::new("exposure", "text").default_value("'public'"),
                ColumnDef::new("first_published_at", "timestamp with time zone"),
                ColumnDef::new("source", "text").default_value("'legacy'"),
                ColumnDef::new("derived_from_id", "integer"),
                ColumnDef::new("checksum_sha256", "text"),
                ColumnDef::new("width", "integer"),
                ColumnDef::new("height", "integer"),
                ColumnDef::new("updated_at", "timestamp with time zone")
                    .default_value("CURRENT_TIMESTAMP"),
                ColumnDef::new("state_since", "timestamp with time zone"),
                ColumnDef::new("references_complete", "boolean").default_value("false"),
                ColumnDef::new("write_token", "uuid"),
                ColumnDef::new("write_lease_until", "timestamp with time zone"),
                ColumnDef::new("producer_key", "text"),
            ],
        },
        TableDef {
            name: "media_references".to_string(),
            columns: vec![
                ColumnDef::new("id", "integer"),
                ColumnDef::new("asset_id", "integer"),
                ColumnDef::new("consumer_type", "text"),
                ColumnDef::new("consumer_id", "text"),
                ColumnDef::new("slot", "text"),
                ColumnDef::new("requires_public", "boolean").default_value("false"),
                ColumnDef::new("expires_at", "timestamp with time zone"),
                ColumnDef::new("created_at", "timestamp with time zone")
                    .default_value("CURRENT_TIMESTAMP"),
            ],
        },
        TableDef {
            name: "media_url_aliases".to_string(),
            columns: vec![
                ColumnDef::new("id", "integer"),
                ColumnDef::new("local_path", "text"),
                ColumnDef::new("asset_id", "integer"),
                ColumnDef::new("created_at", "timestamp with time zone")
                    .default_value("CURRENT_TIMESTAMP"),
            ],
        },
        TableDef {
            name: "media_migration_jobs".to_string(),
            columns: vec![
                ColumnDef::new("id", "integer"),
                ColumnDef::new("source_kind", "text"),
                ColumnDef::new("source_key", "text"),
                ColumnDef::new("asset_id", "integer"),
                ColumnDef::new("copy_state", "text").default_value("'pending'"),
                ColumnDef::new("verify_state", "text").default_value("'pending'"),
                ColumnDef::new("switch_state", "text").default_value("'pending'"),
                ColumnDef::new("error_code", "text"),
                ColumnDef::new("cursor", "text"),
                ColumnDef::new("batch_version", "integer").default_value("1"),
                ColumnDef::new("created_at", "timestamp with time zone")
                    .default_value("CURRENT_TIMESTAMP"),
                ColumnDef::new("updated_at", "timestamp with time zone")
                    .default_value("CURRENT_TIMESTAMP"),
            ],
        },
        TableDef {
            name: "phantasi_source_applications".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "kind".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'friend'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "site_name".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "site_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "feed_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "description".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "applicant_name".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "applicant_email".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "applicant_user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "applicant_ip".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "result_source_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "review_note".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reviewed_by".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reviewed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
    ]
}
