//! Expected Agent-related DB table definitions (tasks, sessions, messages, notifications, persona).
use super::types::{ColumnDef, TableDef};

pub(crate) fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "agent_tasks".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "recipe_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "current_step".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "total_steps".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "step_results".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "execution_context".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "recipe".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "pending_question".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "progress".into(),
                    data_type: "smallint".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "error".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "original_request".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "session_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "lane_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "started_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "completed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "heartbeat_claims".to_string(),
            columns: vec![
                ColumnDef {
                    name: "task_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "minute_bucket".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'running'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "claimed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "completed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_sessions".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "context".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "archived".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_active_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_messages".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "session_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "task_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "role".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_notifications".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "notification_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "priority".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'normal'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "body".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "read".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_task_presets".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "input".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "preset_type".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'history'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "parsed_steps".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "intent_summary".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                // 对话标题
                ColumnDef {
                    name: "title".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                // 完整对话记录 (JSON) - 支持「继续对话」模式
                ColumnDef {
                    name: "conversation_data".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_used_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "use_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("1".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_persona".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "text".into(),
                    default_value: Some("''::text".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "personality".into(),
                    data_type: "text".into(),
                    default_value: Some("''::text".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "persona_json".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "visual_profile".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "portrait_asset_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "portrait_generation".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_asset_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_generation".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_by".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_addressee_state".to_string(),
            columns: vec![
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mood".into(),
                    data_type: "double precision".into(),
                    default_value: Some("70".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "arousal".into(),
                    data_type: "double precision".into(),
                    default_value: Some("50".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "emotion".into(),
                    data_type: "double precision".into(),
                    default_value: Some("50".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "emotion_arousal".into(),
                    data_type: "double precision".into(),
                    default_value: Some("50".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "activity".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'idle'::character varying".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "do_not_disturb".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "dnd_start_minute".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "dnd_end_minute".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_user_message_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_proactive_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "music_mood_credited_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mood_settled_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "emotion_settled_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_diary".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "source".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_proactive_messages".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "role".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "event_key".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "notified".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_intentions".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "source_event_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "summary".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reason_code".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'proposed'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "proposal".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "work_session_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "work_run_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "result_summary".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "expires_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "accept_source".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'user'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "agent_autonomy_grants".to_string(),
            columns: vec![
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "allowed_permissions".into(),
                    data_type: "jsonb".into(),
                    default_value: Some("'[]'::jsonb".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "revoked".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
    ]
}
