//! Expected table definitions (tables_core).
use super::types::{ColumnDef, TableDef};

pub(crate) fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "platforms".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "display_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "icon".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "api_endpoint".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "auth_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "enabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "users".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: true,
                },
                ColumnDef {
                    name: "github_id".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef::new("username", "character varying").not_null(),
                ColumnDef {
                    name: "display_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "email".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "github_profile_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "bio".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "location".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "company".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_admin".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "last_login_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                // 本地认证字段
                ColumnDef {
                    name: "password_hash".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "auth_provider".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'github'".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "linked_github_id".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "local_login_disabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "tapp_install_disabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "note_editor_view".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'visual'".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "notification_preferences".into(),
                    data_type: "jsonb".into(),
                    default_value: Some("'{}'::jsonb".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "tapp_list_card_sizes".into(),
                    data_type: "jsonb".into(),
                    default_value: Some("'{}'::jsonb".into()),
                    not_null: true,
                },
                // 在线状态跟踪（base 001）
                ColumnDef {
                    name: "last_seen_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "online_seconds".into(),
                    data_type: "bigint".into(),
                    default_value: Some("0".into()),
                    not_null: true,
                },
                // 站点 owner（base 001）
                ColumnDef {
                    name: "is_owner".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: true,
                },
                // 画像源选择（base 001）：NULL = auto，沿用隐式优先级，故存量库补列即可，无需回填
                ColumnDef {
                    name: "avatar_source_kind".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_source_ref".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_resolved_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                // 名称/简介文案来源（与 avatar_source_* 独立；NULL = auto）
                ColumnDef {
                    name: "profile_text_source_kind".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "profile_text_source_ref".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                // JWT session epoch: durable sessions compare claim tv in authenticate_request.
                // DEFAULT 0 so existing users keep working until first revoke bump.
                ColumnDef {
                    name: "token_version".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: true,
                },
                ColumnDef {
                    name: "locale".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "user_identities".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "provider".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "provider_user_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "provider_username".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "email".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "email_verified".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "profile_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "raw_profile".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "access_token".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "refresh_token".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "token_expires_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_primary".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "linked_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "last_login_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "configurations".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "key".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "value".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "description".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "category".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'general'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_encrypted".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_public".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "platform_metadata".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "platform_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "raw_data".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "fetched_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "metadata_history".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "platform_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "changed_fields".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "old_data".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "new_data".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "change_date".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "activity_events".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata_history_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "platform_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "event_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "title".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "changes".into(),
                    data_type: "jsonb".into(),
                    default_value: Some("'[]'::jsonb".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "change_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "importance".into(),
                    data_type: "smallint".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "occurred_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "platform_reports".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "platform".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "metadata".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "report".into(),
                    data_type: "jsonb".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "report_title".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp without time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
    ]
}
