//! Expected table definitions (tables_federation).
use super::types::{ColumnDef, TableDef};

pub(crate) fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "federation_keys".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "public_key_pem".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "private_key_encrypted".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "key_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "algorithm".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'RSA-SHA256'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "rotated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_remote_actors".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "actor_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "username".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "domain".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "display_name".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "summary".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "inbox_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "outbox_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "shared_inbox_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "public_key_pem".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "public_key_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "software".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mfp_version".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "tapp_capabilities".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_fetched_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_instances".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "domain".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "software".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "software_version".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mfp_version".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "nodeinfo_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "shared_inbox_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "trust_level".into(),
                    data_type: "smallint".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_blocked".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "block_reason".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "total_users".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "active_users_monthly".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "open_registrations".into(),
                    data_type: "boolean".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "tapp_capabilities".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_seen_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_success_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "failure_count".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "failing_since".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_follows".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "remote_actor_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "direction".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "accepted_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_activities".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "remote_actor_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "object_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "object_json".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_local".into(),
                    data_type: "boolean".into(),
                    default_value: Some("true".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "published_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "received_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_delivery_queue".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "target_inbox".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "target_domain".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "attempts".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "max_attempts".into(),
                    data_type: "integer".into(),
                    default_value: Some("12".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "last_attempt_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "lease_token".into(),
                    data_type: "uuid".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "lease_expires_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "next_retry_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "error_message".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_channels".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "channel_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "remote_actor_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "channel_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "tapp_id".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "transport".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'http'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "properties".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "initiated_by".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_activity_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "closed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_channel_messages".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "channel_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "sender_actor".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "payload".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reply_to".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_encrypted".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_rooms".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "room_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "description".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "avatar_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "owner_actor".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "home_server".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "governance_type".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'owner'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "governance_config".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "enabled_tapps".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "shared_data_config".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "distribution_strategy".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'fan-out'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "max_members".into(),
                    data_type: "integer".into(),
                    default_value: Some("50".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_public".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "invite_policy".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'admin-only'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_room_members".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "room_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "actor_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_local".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "local_user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "role".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'member'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "custom_permissions".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "joined_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "invited_by".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                // active | pending (invite not yet accepted) | declined
                ColumnDef {
                    name: "membership_status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'active'".into()),
                    not_null: false,
                },
                // Per-member read cursor for sidebar unread badges (Aro groups).
                ColumnDef {
                    name: "last_read_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_content_filters".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "name".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "filter_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "value".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "enabled".into(),
                    data_type: "boolean".into(),
                    default_value: Some("true".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_policy_settings".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: Some("1".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "min_trust_level".into(),
                    data_type: "smallint".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "allowed_domains".into(),
                    data_type: "jsonb".into(),
                    default_value: Some("'[]'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "auto_discover".into(),
                    data_type: "boolean".into(),
                    default_value: Some("true".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "rate_max_requests".into(),
                    data_type: "bigint".into(),
                    default_value: Some("100".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "rate_window_seconds".into(),
                    data_type: "bigint".into(),
                    default_value: Some("60".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "rate_trusted_multiplier".into(),
                    data_type: "bigint".into(),
                    default_value: Some("5".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_domain_aliases".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "old_base_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "new_base_url".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_object_interactions".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "object_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "kind".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("CURRENT_TIMESTAMP".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_room_messages".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "room_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "sender_actor".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "message_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "payload".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "thread_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reply_to".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "reactions".into(),
                    data_type: "json".into(),
                    default_value: Some("'{}'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_pinned".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_encrypted".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_ring_memberships".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "ring_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "ring_name".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "ring_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "gossip_config".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                // Plain json (not jsonb). SQL ops that need jsonb (@>, ||, jsonb_array_elements)
                // must cast: COALESCE(known_peers, '[]'::json)::jsonb — see federation/ring.rs.
                ColumnDef {
                    name: "known_peers".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "last_sync_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "joined_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_published_content".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "visibility".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'public'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "published_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "updated_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_timeline".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "remote_actor_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "object_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content_preview".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "content_json".into(),
                    data_type: "json".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "is_read".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "is_bookmarked".into(),
                    data_type: "boolean".into(),
                    default_value: Some("false".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "received_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_inbox_receipts".to_string(),
            columns: vec![
                ColumnDef {
                    name: "signer".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "activity_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "inbox_scope".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "body_digest".into(),
                    data_type: "character(64)".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying(16)".into(),
                    default_value: Some("'processing'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "outcome_status".into(),
                    data_type: "smallint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "error_message".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "completed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
        TableDef {
            name: "federation_file_transfers".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "channel_id".into(),
                    data_type: "text".into(),
                    // Channel transfers set a real id; room transfers use empty string + room_id.
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "room_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "owner_user_id".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "transfer_id".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "filename".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "file_size".into(),
                    data_type: "bigint".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "mime_type".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "checksum_sha256".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "direction".into(),
                    data_type: "character varying".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "status".into(),
                    data_type: "character varying".into(),
                    default_value: Some("'pending'".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "chunks_total".into(),
                    data_type: "integer".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "chunks_completed".into(),
                    data_type: "integer".into(),
                    default_value: Some("0".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "local_path".into(),
                    data_type: "text".into(),
                    default_value: None,
                    not_null: false,
                },
                ColumnDef {
                    name: "created_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: Some("now()".into()),
                    not_null: false,
                },
                ColumnDef {
                    name: "completed_at".into(),
                    data_type: "timestamp with time zone".into(),
                    default_value: None,
                    not_null: false,
                },
            ],
        },
    ]
}
