/**
 * 统一图标导出
 * 从 react-icons 和 lucide-react 精确导入需要的图标，保持包体积最小化
 *
 * ⚠️ 重要：不要使用 import * as 语法，否则会导入整个图标库
 */

import type { IconType } from 'react-icons';
import type { LucideIcon } from 'lucide-react';

// ============================================================
// Simple Icons (Si*) - 品牌图标
// ============================================================
import {
  SiSinaweibo,
  SiX,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTiktok,
  SiLinkedin,
  SiReddit,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiSnapchat,
  SiPinterest,
  SiTwitch,
  SiSpotify,
  SiApple,
  SiAppstore,
  SiGoogle,
  SiAmazon,
  SiDouban,
  SiZhihu,
  SiTencentqq,
  SiWechat,
  SiBaidu,
  SiXiaohongshu,
  SiGitlab,
  SiBitbucket,
  SiCodepen,
  SiDribbble,
  SiBehance,
  SiDeviantart,
  SiMedium,
  SiSubstack,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiThreads,
  SiBluesky,
  SiMisskey,
  SiSoundcloud,
  SiBandcamp,
  SiItchdotio,
  SiPlaystation,
  SiNintendoswitch,
  SiEpicgames,
  SiOrigin,
  SiAnilist,
  SiMyanimelist,
  SiLetterboxd,
  SiTrakt,
  SiGoodreads,
  SiLastdotfm,
  SiPixiv,
  SiArtstation,
  SiFlickr,
  SiUnsplash,
  SiProducthunt,
  SiYcombinator,
  SiStackoverflow,
  SiDevdotto,
  SiHashnode,
  SiKaggle,
  SiHuggingface,
  SiFigma,
  SiNotion,
  SiNiconico,
  SiLine,
  SiKakaotalk,
  SiNaver,
  SiVk,
  SiOdnoklassniki,
  SiTumblr,
  SiWordpress,
  SiBlogger,
  SiGithub,
  SiSteam,
  SiNeteasecloudmusic,
  SiBilibili,
  SiMaildotru,
  SiCloudflare,
  SiOpenai,
  SiGooglegemini,
} from 'react-icons/si';

// 导出 Simple Icons
export {
  SiSinaweibo,
  SiX,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTiktok,
  SiLinkedin,
  SiReddit,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiSnapchat,
  SiPinterest,
  SiTwitch,
  SiSpotify,
  SiApple,
  SiAppstore,
  SiGoogle,
  SiAmazon,
  SiDouban,
  SiZhihu,
  SiTencentqq,
  SiWechat,
  SiBaidu,
  SiXiaohongshu,
  SiGitlab,
  SiBitbucket,
  SiCodepen,
  SiDribbble,
  SiBehance,
  SiDeviantart,
  SiMedium,
  SiSubstack,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiThreads,
  SiBluesky,
  SiMisskey,
  SiSoundcloud,
  SiBandcamp,
  SiItchdotio,
  SiPlaystation,
  SiNintendoswitch,
  SiEpicgames,
  SiOrigin,
  SiAnilist,
  SiMyanimelist,
  SiLetterboxd,
  SiTrakt,
  SiGoodreads,
  SiLastdotfm,
  SiPixiv,
  SiArtstation,
  SiFlickr,
  SiUnsplash,
  SiProducthunt,
  SiYcombinator,
  SiStackoverflow,
  SiDevdotto,
  SiHashnode,
  SiKaggle,
  SiHuggingface,
  SiFigma,
  SiNotion,
  SiNiconico,
  SiLine,
  SiKakaotalk,
  SiNaver,
  SiVk,
  SiOdnoklassniki,
  SiTumblr,
  SiWordpress,
  SiBlogger,
  SiGithub,
  SiSteam,
  SiNeteasecloudmusic,
  SiBilibili,
  SiMaildotru,
  SiCloudflare,
  SiOpenai,
  SiGooglegemini
};

// ============================================================
// Font Awesome Icons (Fa*) - 通用图标
// ============================================================
import {
  FaMusic,
  FaVideo,
  FaBroadcastTower,
  FaComments,
  FaGamepad,
  FaShoppingCart,
  FaNewspaper,
  FaCamera,
  FaBook,
  FaGraduationCap,
  FaGlobe,
  FaHome,
  FaStar,
  FaHeart,
  FaRocket,
  FaBolt,
  FaGem,
  FaCrown,
  FaFeather,
  FaLeaf,
  FaPaperPlane,
  FaCompass,
  FaAnchor,
  FaMoon,
  FaSun,
  FaCloud,
  FaFire,
  FaSnowflake,
  FaUmbrella,
  FaMountain,
  FaWater,
  FaCoffee,
  FaPlayCircle,
  FaBlog,
  FaAlipay,
  FaXbox,
  FaEdit,
  FaSave,
  FaTimes,
  FaPlus,
  FaSteam,
  FaTrash,
  FaCheck,
  FaExternalLinkAlt,
  FaExclamationCircle,
  FaChevronDown,
  FaChevronUp,
  FaExpand,
  FaCompress,
  FaChevronLeft,
  FaChevronRight,
  FaCog,
  FaUser,
  FaUsers,
  FaSearch,
  FaEye,
  FaEyeSlash,
  FaCopy,
  FaDownload,
  FaUpload,
  FaSync,
  FaSyncAlt,
  FaSpinner,
  FaInfoCircle,
  FaQuestionCircle,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaLink,
  FaUnlink,
  FaLock,
  FaUnlock,
  FaKey,
  FaSignInAlt,
  FaSignOutAlt,
  FaEnvelope,
  FaBell,
  FaBellSlash,
  FaImage,
  FaImages,
  FaFileAlt,
  FaFolder,
  FaFolderOpen,
  FaCalendar,
  FaCalendarAlt,
  FaClock,
  FaHistory,
  FaRedo,
  FaUndo,
  FaArrowUp,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaSort,
  FaSortUp,
  FaSortDown,
  FaFilter,
  FaList,
  FaTh,
  FaThLarge,
  FaGripVertical,
  FaGripHorizontal,
  FaEllipsisH,
  FaEllipsisV,
  FaBars,
  FaPalette,
  FaPaintBrush,
  FaMagic,
  FaWrench,
  FaTools,
  FaSlidersH,
  FaDatabase,
  FaServer,
  FaCode,
  FaTerminal,
  FaBug,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaRobot,
  FaBrain,
  FaHdd,
  FaLightbulb,
  FaTwitter,
  FaGithub,
  FaPlay,
  FaPause,
  FaFreeCodeCamp,
  FaVolumeUp,
  FaMicrophone,
  FaHeadphones,
  FaClipboard,
  FaExchangeAlt,
} from 'react-icons/fa';

// 导出 Font Awesome
export {
  FaMusic,
  FaVideo,
  FaBroadcastTower,
  FaComments,
  FaGamepad,
  FaShoppingCart,
  FaNewspaper,
  FaCamera,
  FaBook,
  FaGraduationCap,
  FaGlobe,
  FaHome,
  FaStar,
  FaHeart,
  FaRocket,
  FaBolt,
  FaGem,
  FaCrown,
  FaFeather,
  FaLeaf,
  FaPaperPlane,
  FaCompass,
  FaAnchor,
  FaMoon,
  FaSun,
  FaCloud,
  FaFire,
  FaSnowflake,
  FaUmbrella,
  FaMountain,
  FaWater,
  FaCoffee,
  FaPlayCircle,
  FaBlog,
  FaAlipay,
  FaXbox,
  FaEdit,
  FaSave,
  FaTimes,
  FaPlus,
  FaSteam,
  FaTrash,
  FaCheck,
  FaExternalLinkAlt,
  FaExclamationCircle,
  FaChevronDown,
  FaChevronUp,
  FaExpand,
  FaCompress,
  FaChevronLeft,
  FaChevronRight,
  FaCog,
  FaUser,
  FaUsers,
  FaSearch,
  FaEye,
  FaEyeSlash,
  FaCopy,
  FaDownload,
  FaUpload,
  FaSync,
  FaSyncAlt,
  FaSpinner,
  FaInfoCircle,
  FaQuestionCircle,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaLink,
  FaUnlink,
  FaLock,
  FaUnlock,
  FaKey,
  FaSignInAlt,
  FaSignOutAlt,
  FaEnvelope,
  FaBell,
  FaBellSlash,
  FaImage,
  FaImages,
  FaFileAlt,
  FaFolder,
  FaFolderOpen,
  FaCalendar,
  FaCalendarAlt,
  FaClock,
  FaHistory,
  FaRedo,
  FaUndo,
  FaArrowUp,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaSort,
  FaSortUp,
  FaSortDown,
  FaFilter,
  FaList,
  FaTh,
  FaThLarge,
  FaGripVertical,
  FaGripHorizontal,
  FaEllipsisH,
  FaEllipsisV,
  FaBars,
  FaPalette,
  FaPaintBrush,
  FaMagic,
  FaWrench,
  FaTools,
  FaSlidersH,
  FaDatabase,
  FaServer,
  FaCode,
  FaTerminal,
  FaBug,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaRobot,
  FaBrain,
  FaHdd,
  FaLightbulb,
  FaTwitter,
  FaGithub,
  FaPlay,
  FaPause,
  FaFreeCodeCamp,
  FaVolumeUp,
  FaMicrophone,
  FaHeadphones,
  FaClipboard,
  FaExchangeAlt,
};

// ============================================================
// Font Awesome 6 Icons (Fa6*) - 用于 FaGrip 等
// ============================================================
import { FaGrip } from 'react-icons/fa6';
export { FaGrip };

// ============================================================
// Lucide Icons (Lu*) - 用于 Brew 阅读器等现代 UI
// ============================================================
import {
  // 导航 & 方向
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronDown as LuChevronDown,
  ChevronUp as LuChevronUp,
  ArrowRight as LuArrowRight,
  ArrowUpDown as LuArrowUpDown,

  // 操作
  Plus as LuPlus,
  Minus as LuMinus,
  X as LuX,
  Check as LuCheck,
  Edit3 as LuEdit3,
  Trash2 as LuTrash2,
  RefreshCw as LuRefreshCw,
  Download as LuDownload,
  Upload as LuUpload,
  Search as LuSearch,
  Send as LuSend,
  Copy as LuCopy,
  Reply as LuReply,
  Play as LuPlay,
  Pause as LuPause,
  Square as LuSquare,
  SkipBack as LuSkipBack,
  SkipForward as LuSkipForward,

  // 选择 & 复选框
  CheckSquare as LuCheckSquare,
  MinusSquare as LuMinusSquare,
  CheckCircle as LuCheckCircle,

  // 状态 & 反馈
  Loader2 as LuLoader2,
  AlertCircle as LuAlertCircle,
  Eye as LuEye,
  EyeOff as LuEyeOff,

  // 内容 & 媒体
  Star as LuStar,
  FileText as LuFileText,
  Folder as LuFolder,
  FolderOpen as LuFolderOpen,
  MessageSquare as LuMessageSquare,
  Mic as LuMic,
  Volume2 as LuVolume2,

  // RSS & 链接
  Rss as LuRss,
  Link as LuLink,
  ExternalLink as LuExternalLink,
  Globe as LuGlobe,

  // 时间 & 用户
  Clock as LuClock,
  Calendar as LuCalendar,
  User as LuUser,

  // 布局 & 视图
  List as LuList,
  Inbox as LuInbox,
  GripVertical as LuGripVertical,
  AlignJustify as LuAlignJustify,
  MoreHorizontal as LuMoreHorizontal,

  // AI & 特效
  Sparkles as LuSparkles,
  Zap as LuZap,

  // 设置 & 工具
  Settings as LuSettings,
  Palette as LuPalette,
  Tag as LuTag,
  Key as LuKey,
  Keyboard as LuKeyboard,
  Type as LuType,

  // 服务器 & 监控
  Server as LuServer,
  Cloud as LuCloud,
  Monitor as LuMonitor,
  Activity as LuActivity,
  BarChart3 as LuBarChart3,

  // 排序
  Shuffle as LuShuffle,
  SortAsc as LuSortAsc,

  // 图片相关
  ZoomIn as LuZoomIn,
  ZoomOut as LuZoomOut,
  RotateCw as LuRotateCw,
} from 'lucide-react';

// 导出 Lucide Icons
export {
  // 导航 & 方向
  LuChevronLeft,
  LuChevronRight,
  LuChevronDown,
  LuChevronUp,
  LuArrowRight,
  LuArrowUpDown,

  // 操作
  LuPlus,
  LuMinus,
  LuX,
  LuCheck,
  LuEdit3,
  LuTrash2,
  LuRefreshCw,
  LuDownload,
  LuUpload,
  LuSearch,
  LuSend,
  LuCopy,
  LuReply,
  LuPlay,
  LuPause,
  LuSquare,
  LuSkipBack,
  LuSkipForward,

  // 选择 & 复选框
  LuCheckSquare,
  LuMinusSquare,
  LuCheckCircle,

  // 状态 & 反馈
  LuLoader2,
  LuAlertCircle,
  LuEye,
  LuEyeOff,

  // 内容 & 媒体
  LuStar,
  LuFileText,
  LuFolder,
  LuFolderOpen,
  LuMessageSquare,
  LuMic,
  LuVolume2,

  // RSS & 链接
  LuRss,
  LuLink,
  LuExternalLink,
  LuGlobe,

  // 时间 & 用户
  LuClock,
  LuCalendar,
  LuUser,

  // 布局 & 视图
  LuList,
  LuInbox,
  LuGripVertical,
  LuAlignJustify,
  LuMoreHorizontal,

  // AI & 特效
  LuSparkles,
  LuZap,

  // 设置 & 工具
  LuSettings,
  LuPalette,
  LuTag,
  LuKey,
  LuKeyboard,
  LuType,

  // 服务器 & 监控
  LuServer,
  LuCloud,
  LuMonitor,
  LuActivity,
  LuBarChart3,

  // 排序
  LuShuffle,
  LuSortAsc,

  // 图片相关
  LuZoomIn,
  LuZoomOut,
  LuRotateCw,
};

// ============================================================
// 别名
// ============================================================
export const FaXTwitter = SiX;

// ============================================================
// 图标映射表 - 用于动态查找 (getIconByName)
// ============================================================
export const iconMap: Record<string, IconType> = {
  // Simple Icons - 品牌图标
  SiSinaweibo,
  SiX,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTiktok,
  SiLinkedin,
  SiReddit,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiSnapchat,
  SiPinterest,
  SiTwitch,
  SiSpotify,
  SiApple,
  SiAppstore,
  SiGoogle,
  SiAmazon,
  SiDouban,
  SiZhihu,
  SiTencentqq,
  SiWechat,
  SiBaidu,
  SiXiaohongshu,
  SiGitlab,
  SiBitbucket,
  SiCodepen,
  SiDribbble,
  SiBehance,
  SiDeviantart,
  SiMedium,
  SiSubstack,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiThreads,
  SiBluesky,
  SiMisskey,
  SiSoundcloud,
  SiBandcamp,
  SiItchdotio,
  SiPlaystation,
  SiNintendoswitch,
  SiEpicgames,
  SiOrigin,
  SiAnilist,
  SiMyanimelist,
  SiLetterboxd,
  SiTrakt,
  SiGoodreads,
  SiLastdotfm,
  SiPixiv,
  SiArtstation,
  SiFlickr,
  SiUnsplash,
  SiProducthunt,
  SiYcombinator,
  SiStackoverflow,
  SiDevdotto,
  SiHashnode,
  SiKaggle,
  SiHuggingface,
  SiFigma,
  SiNotion,
  SiNiconico,
  SiLine,
  SiKakaotalk,
  SiNaver,
  SiVk,
  SiOdnoklassniki,
  SiTumblr,
  SiWordpress,
  SiBlogger,
  SiGithub,
  SiSteam,
  SiNeteasecloudmusic,
  SiBilibili,
  SiMaildotru,
  // Font Awesome - 通用图标
  FaMusic,
  FaVideo,
  FaBroadcastTower,
  FaComments,
  FaGamepad,
  FaShoppingCart,
  FaNewspaper,
  FaCamera,
  FaBook,
  FaGraduationCap,
  FaGlobe,
  FaHome,
  FaStar,
  FaHeart,
  FaRocket,
  FaBolt,
  FaGem,
  FaCrown,
  FaFeather,
  FaLeaf,
  FaPaperPlane,
  FaCompass,
  FaAnchor,
  FaMoon,
  FaSun,
  FaCloud,
  FaFire,
  FaSnowflake,
  FaUmbrella,
  FaMountain,
  FaWater,
  FaCoffee,
  FaPlayCircle,
  FaBlog,
  FaAlipay,
  FaXbox,
  FaEdit,
  FaSave,
  FaTimes,
  FaPlus,
  FaSteam,
  FaTrash,
  FaCheck,
  FaExternalLinkAlt,
  FaExclamationCircle,
  FaChevronDown,
  FaChevronUp,
  FaExpand,
  FaCompress,
  FaChevronLeft,
  FaChevronRight,
  FaCog,
  FaUser,
  FaUsers,
  FaSearch,
  FaEye,
  FaEyeSlash,
  FaCopy,
  FaDownload,
  FaUpload,
  FaSync,
  FaSyncAlt,
  FaSpinner,
  FaInfoCircle,
  FaQuestionCircle,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaRobot,
  FaBrain,
  FaHdd,
  FaLightbulb,
  FaTwitter,
  FaGithub,
  FaPlay,
  FaPause,
  // Font Awesome 6
  FaGrip,
  FaFreeCodeCamp,
  FaVolumeUp,
  FaMicrophone,
  FaHeadphones,
  FaClipboard,
  FaExchangeAlt,
  // 别名
  FaXTwitter: SiX,
};

/**
 * 根据名称获取图标组件
 * @param name 图标名称（如 "SiGithub", "FaHeart"）
 * @returns 图标组件或 null
 */
export function getIconByName(name: string): IconType | null {
  return iconMap[name] || null;
}

// ============================================================
// 自定义 SVG 图标组件
// ============================================================

/**
 * RSSHub 品牌图标
 * 官方设计：地球 + 网状图案，代表全球化的 RSS 聚合
 * Simple Icons 中没有此图标，使用自定义 SVG
 */
export const RSSHubIcon = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="currentColor">
    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"/>
  </svg>
);

// 为了兼容性，导出 NotionIcon 别名（使用 SiNotion）
export const NotionIcon = SiNotion;

// 导出类型
export type { IconType, LucideIcon };
