/**
 * 统一图标导出
 * 从 react-icons 和 lucide-react 精确导入需要的图标，保持包体积最小化
 *
 * ⚠️ 重要：不要使用 import * as 语法，否则会导入整个图标库
 */

import type { LucideIcon } from 'lucide-react'
import type { IconType } from 'react-icons'

// ============================================================
// Lucide Icons (Lu*) - 用于 Brew 阅读器等现代 UI
// ============================================================
import {
  Activity as LuActivity,
  AlertCircle as LuAlertCircle,
  AlignJustify as LuAlignJustify,
  ArrowRight as LuArrowRight,
  ArrowUpDown as LuArrowUpDown,
  BarChart3 as LuBarChart3,

  Calendar as LuCalendar,
  Check as LuCheck,
  CheckCircle as LuCheckCircle,
  // 选择 & 复选框
  CheckSquare as LuCheckSquare,
  ChevronDown as LuChevronDown,
  // 导航 & 方向
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronUp as LuChevronUp,
  // 时间 & 用户
  Clock as LuClock,
  Cloud as LuCloud,
  Copy as LuCopy,
  Download as LuDownload,
  Edit3 as LuEdit3,
  ExternalLink as LuExternalLink,
  Eye as LuEye,
  EyeOff as LuEyeOff,
  FileText as LuFileText,
  Folder as LuFolder,

  FolderOpen as LuFolderOpen,
  Globe as LuGlobe,
  GripVertical as LuGripVertical,

  Inbox as LuInbox,
  Key as LuKey,
  Keyboard as LuKeyboard,
  Link as LuLink,

  // 布局 & 视图
  List as LuList,
  // 状态 & 反馈
  Loader2 as LuLoader2,
  MessageSquare as LuMessageSquare,
  Mic as LuMic,
  Minus as LuMinus,
  MinusSquare as LuMinusSquare,
  Monitor as LuMonitor,

  MoreHorizontal as LuMoreHorizontal,
  Palette as LuPalette,
  Pause as LuPause,
  Play as LuPlay,

  // 操作
  Plus as LuPlus,
  RefreshCw as LuRefreshCw,
  Reply as LuReply,

  RotateCw as LuRotateCw,
  // RSS & 链接
  Rss as LuRss,
  Search as LuSearch,
  Send as LuSend,
  // 服务器 & 监控
  Server as LuServer,

  // 设置 & 工具
  Settings as LuSettings,
  // 排序
  Shuffle as LuShuffle,

  SkipBack as LuSkipBack,
  SkipForward as LuSkipForward,
  SortAsc as LuSortAsc,
  // AI & 特效
  Sparkles as LuSparkles,
  Square as LuSquare,
  // 内容 & 媒体
  Star as LuStar,

  Tag as LuTag,
  Trash2 as LuTrash2,
  Type as LuType,
  Upload as LuUpload,
  User as LuUser,

  Volume2 as LuVolume2,
  X as LuX,

  Zap as LuZap,
  // 图片相关
  ZoomIn as LuZoomIn,
  ZoomOut as LuZoomOut,
} from 'lucide-react'

// ============================================================
// Font Awesome Icons (Fa*) - 通用图标
// ============================================================
import {
  FaAlipay,
  FaAnchor,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBars,
  FaBell,
  FaBellSlash,
  FaBlog,
  FaBolt,
  FaBook,
  FaBrain,
  FaBroadcastTower,
  FaBug,
  FaCalendar,
  FaCalendarAlt,
  FaCamera,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaClipboard,
  FaClock,
  FaCloud,
  FaCode,
  FaCoffee,
  FaCog,
  FaComments,
  FaCompass,
  FaCompress,
  FaCopy,
  FaCrown,
  FaDatabase,
  FaDownload,
  FaEdit,
  FaEllipsisH,
  FaEllipsisV,
  FaEnvelope,
  FaExchangeAlt,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExpand,
  FaExternalLinkAlt,
  FaEye,
  FaEyeSlash,
  FaFeather,
  FaFileAlt,
  FaFilter,
  FaFire,
  FaFolder,
  FaFolderOpen,
  FaFreeCodeCamp,
  FaGamepad,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGripHorizontal,
  FaGripVertical,
  FaHdd,
  FaHeadphones,
  FaHeart,
  FaHistory,
  FaHome,
  FaImage,
  FaImages,
  FaInfoCircle,
  FaKey,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaList,
  FaLock,
  FaMagic,
  FaMicrophone,
  FaMoon,
  FaMountain,
  FaMusic,
  FaNewspaper,
  FaPaintBrush,
  FaPalette,
  FaPaperPlane,
  FaPause,
  FaPlay,
  FaPlayCircle,
  FaPlus,
  FaQuestionCircle,
  FaRedo,
  FaRobot,
  FaRocket,
  FaSave,
  FaSearch,
  FaServer,
  FaShoppingCart,
  FaSignInAlt,
  FaSignOutAlt,
  FaSlidersH,
  FaSnowflake,
  FaSort,
  FaSortDown,
  FaSortUp,
  FaSpinner,
  FaStar,
  FaSteam,
  FaSun,
  FaSync,
  FaSyncAlt,
  FaTerminal,
  FaTh,
  FaThLarge,
  FaTimes,
  FaTimesCircle,
  FaTools,
  FaTrash,
  FaTwitter,
  FaUmbrella,
  FaUndo,
  FaUnlink,
  FaUnlock,
  FaUpload,
  FaUser,
  FaUsers,
  FaVideo,
  FaVolumeUp,
  FaWater,
  FaWrench,
  FaXbox,
} from 'react-icons/fa'

// ============================================================
// Font Awesome 6 Icons (Fa6*) - 用于 FaGrip 等
// ============================================================
import { FaGrip } from 'react-icons/fa6'

// ============================================================
// Simple Icons (Si*) - 品牌图标
// ============================================================
import {
  SiAmazon,
  SiAnilist,
  SiApple,
  SiAppstore,
  SiArtstation,
  SiBaidu,
  SiBandcamp,
  SiBehance,
  SiBilibili,
  SiBitbucket,
  SiBlogger,
  SiBluesky,
  SiBuymeacoffee,
  SiCloudflare,
  SiCodepen,
  SiDevdotto,
  SiDeviantart,
  SiDiscord,
  SiDouban,
  SiDribbble,
  SiEpicgames,
  SiFacebook,
  SiFigma,
  SiFlickr,
  SiGithub,
  SiGitlab,
  SiGoodreads,
  SiGoogle,
  SiGooglegemini,
  SiHashnode,
  SiHuggingface,
  SiInstagram,
  SiItchdotio,
  SiKaggle,
  SiKakaotalk,
  SiKofi,
  SiLastdotfm,
  SiLetterboxd,
  SiLine,
  SiLinkedin,
  SiMaildotru,
  SiMastodon,
  SiMedium,
  SiMisskey,
  SiMyanimelist,
  SiNaver,
  SiNeteasecloudmusic,
  SiNiconico,
  SiNintendoswitch,
  SiNotion,
  SiOdnoklassniki,
  SiOpenai,
  SiOrigin,
  SiPatreon,
  SiPinterest,
  SiPixiv,
  SiPlaystation,
  SiProducthunt,
  SiReddit,
  SiSinaweibo,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiStackoverflow,
  SiSteam,
  SiSubstack,
  SiTelegram,
  SiTencentqq,
  SiThreads,
  SiTiktok,
  SiTrakt,
  SiTumblr,
  SiTwitch,
  SiUnsplash,
  SiVk,
  SiWechat,
  SiWhatsapp,
  SiWordpress,
  SiX,
  SiXiaohongshu,
  SiYcombinator,
  SiYoutube,
  SiZhihu,
} from 'react-icons/si'

// 导出 Simple Icons
export {
  SiAmazon,
  SiAnilist,
  SiApple,
  SiAppstore,
  SiArtstation,
  SiBaidu,
  SiBandcamp,
  SiBehance,
  SiBilibili,
  SiBitbucket,
  SiBlogger,
  SiBluesky,
  SiBuymeacoffee,
  SiCloudflare,
  SiCodepen,
  SiDevdotto,
  SiDeviantart,
  SiDiscord,
  SiDouban,
  SiDribbble,
  SiEpicgames,
  SiFacebook,
  SiFigma,
  SiFlickr,
  SiGithub,
  SiGitlab,
  SiGoodreads,
  SiGoogle,
  SiGooglegemini,
  SiHashnode,
  SiHuggingface,
  SiInstagram,
  SiItchdotio,
  SiKaggle,
  SiKakaotalk,
  SiKofi,
  SiLastdotfm,
  SiLetterboxd,
  SiLine,
  SiLinkedin,
  SiMaildotru,
  SiMastodon,
  SiMedium,
  SiMisskey,
  SiMyanimelist,
  SiNaver,
  SiNeteasecloudmusic,
  SiNiconico,
  SiNintendoswitch,
  SiNotion,
  SiOdnoklassniki,
  SiOpenai,
  SiOrigin,
  SiPatreon,
  SiPinterest,
  SiPixiv,
  SiPlaystation,
  SiProducthunt,
  SiReddit,
  SiSinaweibo,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiStackoverflow,
  SiSteam,
  SiSubstack,
  SiTelegram,
  SiTencentqq,
  SiThreads,
  SiTiktok,
  SiTrakt,
  SiTumblr,
  SiTwitch,
  SiUnsplash,
  SiVk,
  SiWechat,
  SiWhatsapp,
  SiWordpress,
  SiX,
  SiXiaohongshu,
  SiYcombinator,
  SiYoutube,
  SiZhihu,
}

// 导出 Font Awesome
export {
  FaAlipay,
  FaAnchor,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBars,
  FaBell,
  FaBellSlash,
  FaBlog,
  FaBolt,
  FaBook,
  FaBrain,
  FaBroadcastTower,
  FaBug,
  FaCalendar,
  FaCalendarAlt,
  FaCamera,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaClipboard,
  FaClock,
  FaCloud,
  FaCode,
  FaCoffee,
  FaCog,
  FaComments,
  FaCompass,
  FaCompress,
  FaCopy,
  FaCrown,
  FaDatabase,
  FaDownload,
  FaEdit,
  FaEllipsisH,
  FaEllipsisV,
  FaEnvelope,
  FaExchangeAlt,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExpand,
  FaExternalLinkAlt,
  FaEye,
  FaEyeSlash,
  FaFeather,
  FaFileAlt,
  FaFilter,
  FaFire,
  FaFolder,
  FaFolderOpen,
  FaFreeCodeCamp,
  FaGamepad,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGripHorizontal,
  FaGripVertical,
  FaHdd,
  FaHeadphones,
  FaHeart,
  FaHistory,
  FaHome,
  FaImage,
  FaImages,
  FaInfoCircle,
  FaKey,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaList,
  FaLock,
  FaMagic,
  FaMicrophone,
  FaMoon,
  FaMountain,
  FaMusic,
  FaNewspaper,
  FaPaintBrush,
  FaPalette,
  FaPaperPlane,
  FaPause,
  FaPlay,
  FaPlayCircle,
  FaPlus,
  FaQuestionCircle,
  FaRedo,
  FaRobot,
  FaRocket,
  FaSave,
  FaSearch,
  FaServer,
  FaShoppingCart,
  FaSignInAlt,
  FaSignOutAlt,
  FaSlidersH,
  FaSnowflake,
  FaSort,
  FaSortDown,
  FaSortUp,
  FaSpinner,
  FaStar,
  FaSteam,
  FaSun,
  FaSync,
  FaSyncAlt,
  FaTerminal,
  FaTh,
  FaThLarge,
  FaTimes,
  FaTimesCircle,
  FaTools,
  FaTrash,
  FaTwitter,
  FaUmbrella,
  FaUndo,
  FaUnlink,
  FaUnlock,
  FaUpload,
  FaUser,
  FaUsers,
  FaVideo,
  FaVolumeUp,
  FaWater,
  FaWrench,
  FaXbox,
}
export { FaGrip }

// 导出 Lucide Icons
export {
  LuActivity,
  LuAlertCircle,
  LuAlignJustify,
  LuArrowRight,
  LuArrowUpDown,
  LuBarChart3,

  LuCalendar,
  LuCheck,
  LuCheckCircle,
  // 选择 & 复选框
  LuCheckSquare,
  LuChevronDown,
  // 导航 & 方向
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  // 时间 & 用户
  LuClock,
  LuCloud,
  LuCopy,
  LuDownload,
  LuEdit3,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileText,
  LuFolder,

  LuFolderOpen,
  LuGlobe,
  LuGripVertical,

  LuInbox,
  LuKey,
  LuKeyboard,
  LuLink,

  // 布局 & 视图
  LuList,
  // 状态 & 反馈
  LuLoader2,
  LuMessageSquare,
  LuMic,
  LuMinus,
  LuMinusSquare,
  LuMonitor,

  LuMoreHorizontal,
  LuPalette,
  LuPause,
  LuPlay,

  // 操作
  LuPlus,
  LuRefreshCw,
  LuReply,

  LuRotateCw,
  // RSS & 链接
  LuRss,
  LuSearch,
  LuSend,
  // 服务器 & 监控
  LuServer,

  // 设置 & 工具
  LuSettings,
  // 排序
  LuShuffle,

  LuSkipBack,
  LuSkipForward,
  LuSortAsc,
  // AI & 特效
  LuSparkles,
  LuSquare,
  // 内容 & 媒体
  LuStar,

  LuTag,
  LuTrash2,
  LuType,
  LuUpload,
  LuUser,

  LuVolume2,
  LuX,

  LuZap,
  // 图片相关
  LuZoomIn,
  LuZoomOut,
}

// ============================================================
// 别名
// ============================================================
export const FaXTwitter = SiX

// ============================================================
// 图标映射表 - 用于动态查找 (getIconByName)
// ============================================================
export const iconMap: Record<string, IconType> = {
  // Simple Icons - 品牌图标
  SiSinaweibo,
  SiX,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTiktok,
  SiLinkedin,
  SiReddit,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiSnapchat,
  SiPinterest,
  SiTwitch,
  SiSpotify,
  SiApple,
  SiAppstore,
  SiGoogle,
  SiAmazon,
  SiDouban,
  SiZhihu,
  SiTencentqq,
  SiWechat,
  SiBaidu,
  SiXiaohongshu,
  SiGitlab,
  SiBitbucket,
  SiCodepen,
  SiDribbble,
  SiBehance,
  SiDeviantart,
  SiMedium,
  SiSubstack,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiThreads,
  SiBluesky,
  SiMisskey,
  SiSoundcloud,
  SiBandcamp,
  SiItchdotio,
  SiPlaystation,
  SiNintendoswitch,
  SiEpicgames,
  SiOrigin,
  SiAnilist,
  SiMyanimelist,
  SiLetterboxd,
  SiTrakt,
  SiGoodreads,
  SiLastdotfm,
  SiPixiv,
  SiArtstation,
  SiFlickr,
  SiUnsplash,
  SiProducthunt,
  SiYcombinator,
  SiStackoverflow,
  SiDevdotto,
  SiHashnode,
  SiKaggle,
  SiHuggingface,
  SiFigma,
  SiNotion,
  SiNiconico,
  SiLine,
  SiKakaotalk,
  SiNaver,
  SiVk,
  SiOdnoklassniki,
  SiTumblr,
  SiWordpress,
  SiBlogger,
  SiGithub,
  SiSteam,
  SiNeteasecloudmusic,
  SiBilibili,
  SiMaildotru,
  // Font Awesome - 通用图标
  FaMusic,
  FaVideo,
  FaBroadcastTower,
  FaComments,
  FaGamepad,
  FaShoppingCart,
  FaNewspaper,
  FaCamera,
  FaBook,
  FaGraduationCap,
  FaGlobe,
  FaHome,
  FaStar,
  FaHeart,
  FaRocket,
  FaBolt,
  FaGem,
  FaCrown,
  FaFeather,
  FaLeaf,
  FaPaperPlane,
  FaCompass,
  FaAnchor,
  FaMoon,
  FaSun,
  FaCloud,
  FaFire,
  FaSnowflake,
  FaUmbrella,
  FaMountain,
  FaWater,
  FaCoffee,
  FaPlayCircle,
  FaBlog,
  FaAlipay,
  FaXbox,
  FaEdit,
  FaSave,
  FaTimes,
  FaPlus,
  FaSteam,
  FaTrash,
  FaCheck,
  FaExternalLinkAlt,
  FaExclamationCircle,
  FaChevronDown,
  FaChevronUp,
  FaExpand,
  FaCompress,
  FaChevronLeft,
  FaChevronRight,
  FaCog,
  FaUser,
  FaUsers,
  FaSearch,
  FaEye,
  FaEyeSlash,
  FaCopy,
  FaDownload,
  FaUpload,
  FaSync,
  FaSyncAlt,
  FaSpinner,
  FaInfoCircle,
  FaQuestionCircle,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaRobot,
  FaBrain,
  FaHdd,
  FaLightbulb,
  FaTwitter,
  FaGithub,
  FaPlay,
  FaPause,
  // Font Awesome 6
  FaGrip,
  FaFreeCodeCamp,
  FaVolumeUp,
  FaMicrophone,
  FaHeadphones,
  FaClipboard,
  FaExchangeAlt,
  // 别名
  FaXTwitter: SiX,
}

/**
 * 根据名称获取图标组件
 * @param name 图标名称（如 "SiGithub", "FaHeart"）
 * @returns 图标组件或 null
 */
export function getIconByName(name: string): IconType | null {
  return iconMap[name] || null
}

// ============================================================
// 自定义 SVG 图标组件
// ============================================================

/**
 * RSSHub 品牌图标
 * 官方设计：地球 + 网状图案，代表全球化的 RSS 聚合
 * Simple Icons 中没有此图标，使用自定义 SVG
 */
export function RSSHubIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
    </svg>
  )
}

// 为了兼容性，导出 NotionIcon 别名（使用 SiNotion）
export const NotionIcon = SiNotion

// 导出类型
export type { IconType, LucideIcon }
